"""Artemis routing harness: the frozen half of the AutoResearch contract.

DO NOT EDIT THIS FILE. Agents edit experiment.py (or a copy of it in trials/);
humans change this file, and every change shows up in its fingerprint.

The question
------------
Given the same short time limit on one CPU core, can the lab's agents build a
capacitated vehicle routing (CVRP) solver that gets closer to the best-known
solutions of the CVRPLIB X benchmark than PyVRP's default solver, a
state-of-the-art open-source library? And, in longer runs, can any of its
routes beat a published best-known solution outright?

The judge
---------
The harness, not the experiment, checks every solution and computes its
length. A solution is a list of routes; each route is a list of customer
numbers 1..n, and the depot (0) is implied at both ends. It is valid only if
every customer is visited exactly once and no route carries more than the
vehicle capacity. Its cost is the sum of Euclidean distances rounded to the
nearest integer, the CVRPLIB convention; prepare_data.py re-computed all 100
published best-known costs with this code and matched every one exactly.

Each solve() runs in its own process (runner.py, also frozen), in a new
process group, from an empty folder, with one BLAS thread. The harness itself
measures the time from "ready" to the answer and the CPU the process used.

Pre-registered definitions (fixed 2026-10-07 by Claude, owner Peter Alesso)
---------------------------------------------------------------------------
Time limit:     3.0 seconds per 100 customers (e.g. 13.44 s for 448 customers),
                one CPU core. The answer must arrive within 1.03 x the limit
                plus 0.5 s of the runner reporting ready.
Primary metric: mean gap to the best-known solution over the val instances,
                gap = 100 * (cost - BKS) / BKS, seed 0. Lower is better.
Final test:     test and scale, seeds 0, 1 and 2, for the experiment and the
                frozen reference; reported with a paired comparison (mean
                difference, 95 percent bootstrap interval, sign test).
Also reported:  median and worst gap, and on how many instances the
                experiment beat the frozen PyVRP reference (same seed).
Splits:         see prepare_data.py. "train" and "hunt" may be probed freely;
                "val" is the loop's pool (60 evaluations and 20 rechecks per
                run); "test" and "scale" are used exactly once, by `final`.
Records:        `verify` checks a solution file and reports whether it beats
                the BKS in the frozen snapshot (val, test and scale instances
                only after `final`).

Commands
--------
    python lab/cvrp/harness.py fingerprint
    python lab/cvrp/harness.py describe
    python lab/cvrp/harness.py baselines
    python lab/cvrp/harness.py probe --experiment lab/cvrp/trials/NAME.py --instances X-n101-k25,X-n120-k6
    python lab/cvrp/harness.py evaluate --experiment lab/cvrp/trials/NAME.py --note "..."
    python lab/cvrp/harness.py recheck --experiment lab/cvrp/trials/NAME.py
    python lab/cvrp/harness.py final            # once, at the very end
    python lab/cvrp/harness.py verify --instance X-n801-k40 --solution path/to/file.sol

Every evaluation writes a "started" row to the ledger before it runs and a
result row ("ok" or "invalid") after; budgets count the started rows, so an
interrupted evaluation still counts.
"""

from __future__ import annotations

import argparse
import ast
import contextlib
import csv
import gzip
import hashlib
import json
import math
import os
import queue
import secrets
import signal
import statistics
import subprocess
import sys
import tempfile
import threading
import time
import uuid
from datetime import datetime, timezone
from pathlib import Path

import numpy as np

try:  # Linux and macOS (the lab's sandbox). Windows lacks both modules.
    import fcntl
    import resource
except ImportError:  # pragma: no cover - only on Windows
    fcntl = None
    resource = None

HERE = Path(__file__).resolve().parent
REPO_ROOT = HERE.parent.parent
DATA_DIR = HERE / "data"
SNAPSHOT = DATA_DIR / "instances.json.gz"
MANIFEST = DATA_DIR / "manifest.json"
REFERENCE = HERE / "reference.py"
RUNNER = HERE / "runner.py"
DEFAULT_EXPERIMENT = HERE / "experiment.py"
# Humans may point local checks elsewhere; the lab never sets this.
RUNS_DIR = Path(os.environ.get("ARTEMIS_RUNS_DIR", REPO_ROOT / "runs" / "cvrp"))
LEDGER = RUNS_DIR / "ledger.tsv"
DETAILS_DIR = RUNS_DIR / "details"
FINAL_RESULT = RUNS_DIR / "final_test.json"
FINAL_STARTED = RUNS_DIR / "final_started"
RECORDS = RUNS_DIR / "records.tsv"
LOCK = RUNS_DIR / "solver.lock"

# ---- pre-registered definitions (see module docstring) --------------------
SECONDS_PER_100_CUSTOMERS = 3.0
SEED = 0
RECHECK_SEEDS = (1, 2)
FINAL_SEEDS = (0, 1, 2)          # run 2: the final test repeats every held-out problem 3 times
BOOTSTRAP_DRAWS = 10_000

# ---- rules of the game ----------------------------------------------------
EXPERIMENT_BUDGET = 60           # val evaluations per ledger (one lab run)
RECHECK_BUDGET = 20              # extra-seed val re-runs for the Skeptic
READY_TIMEOUT_S = 120.0          # imports and setup before solve() starts
TIME_FACTOR = 1.03               # the answer must come within 1.03 x limit + 0.5 s
TIME_GRACE_S = 0.5
KILL_EXTRA_S = 3.0               # after which the process group is killed
CPU_FACTOR = 1.10                # CPU may not exceed 1.10 x limit + 4 s (imports)
CPU_GRACE_S = 4.0
MAX_PROBE_SEEDS = 3

# ---- what an experiment may contain ------------------------------------------
MAX_EXPERIMENT_BYTES = 40_000    # long files could smuggle in hard-coded routes
MAX_NUMERIC_CONSTANTS = 300
MAX_LITERAL_ELEMENTS = 50
MAX_STRING_CHARS = 2_000         # outside docstrings
ALLOWED_IMPORTS = frozenset({
    "numpy", "pyvrp", "math", "heapq", "itertools", "collections", "random", "time",
    "typing", "functools", "dataclasses", "bisect", "statistics", "array", "copy",
    "enum", "abc", "__future__",
})
BANNED_NAMES = frozenset({
    "open", "exec", "eval", "compile", "__import__", "globals", "locals", "vars",
    "getattr", "setattr", "delattr", "breakpoint", "input", "memoryview", "help",
    "exit", "quit", "sys", "os", "io", "types", "inspect", "importlib", "builtins",
})
BANNED_ATTRIBUTES = frozenset({
    "fromfile", "tofile", "save", "savez", "savez_compressed", "load", "loadtxt",
    "savetxt", "genfromtxt", "memmap", "DataSource", "fromregex", "ctypeslib", "lib",
    "core", "_core", "testing", "f2py", "distutils", "read", "read_solution", "write",
    "os", "sys", "subprocess", "system", "popen",
})
LEDGER_FIELDS = [
    "utc", "kind", "split", "experiment", "experiment_sha12", "git_commit",
    "status", "seeds", "instances", "mean_gap_pct", "median_gap_pct",
    "worst_gap_pct", "beats_reference", "seconds", "cpu_seconds",
    "harness_sha12", "snapshot_sha12", "note",
]


class HarnessError(RuntimeError):
    """A problem the harness explains in plain language instead of a traceback."""


# ---------------------------------------------------------------- integrity
def sha256_file(path: Path) -> str:
    """Return the hex SHA-256 of the file at *path*."""
    digest = hashlib.sha256()
    with open(path, "rb") as handle:
        for block in iter(lambda: handle.read(1 << 20), b""):
            digest.update(block)
    return digest.hexdigest()


def fingerprint() -> dict[str, str]:
    """Return the SHA-256 of the harness, runner, reference solver and snapshot."""
    return {
        "harness": sha256_file(Path(__file__).resolve()),
        "runner": sha256_file(RUNNER),
        "reference": sha256_file(REFERENCE),
        "snapshot": sha256_file(SNAPSHOT) if SNAPSHOT.exists() else "missing",
    }


def load_instances() -> dict[str, dict]:
    """Load the frozen snapshot after checking it against its manifest."""
    if not SNAPSHOT.exists() or not MANIFEST.exists():
        raise HarnessError("The data snapshot is missing. A human builds it once with "
                           "`python lab/cvrp/prepare_data.py` and commits lab/cvrp/data/.")
    manifest = json.loads(MANIFEST.read_text(encoding="utf-8"))
    actual = sha256_file(SNAPSHOT)
    if actual != manifest.get("sha256"):
        raise HarnessError(f"The snapshot does not match its manifest (expected "
                           f"{str(manifest.get('sha256'))[:12]}, found {actual[:12]}). "
                           "Someone changed the data; restore it from git before continuing.")
    with gzip.open(SNAPSHOT, "rt", encoding="utf-8") as handle:
        payload = json.load(handle)
    return {i["name"]: i for i in payload["instances"]}


def split_names(instances: dict[str, dict], split: str) -> list[str]:
    """Instance names in *split*, smallest first."""
    names = [k for k, v in instances.items() if v["split"] == split]
    return sorted(names, key=lambda k: (instances[k]["customers"], k))


def time_limit(instance: dict) -> float:
    """The pre-registered time limit for *instance*, in seconds."""
    return round(SECONDS_PER_100_CUSTOMERS * instance["customers"] / 100.0, 2)


def final_done() -> bool:
    """True once `final` has started (the held-out splits are then spent)."""
    return FINAL_STARTED.exists() or FINAL_RESULT.exists()


# ---------------------------------------------------------------- the judge
def nint(value: float) -> int:
    """CVRPLIB rounding: nearest integer, halves rounded up."""
    return int(math.floor(value + 0.5))


def distance_matrix(coords: list[list[int]]) -> np.ndarray:
    """Rounded Euclidean distances between every pair of nodes."""
    xy = np.asarray(coords, dtype=np.float64)
    diff = xy[:, None, :] - xy[None, :, :]
    return np.floor(np.sqrt((diff ** 2).sum(axis=2)) + 0.5).astype(np.int64)


def check_solution(instance: dict, routes: object) -> int:
    """Validate *routes* for *instance* and return their cost (the judge)."""
    if not isinstance(routes, (list, tuple)):
        raise HarnessError(f"solve() must return a list of routes, got {type(routes).__name__}")
    clean: list[list[int]] = []
    for route in routes:
        if not isinstance(route, (list, tuple)):
            raise HarnessError("each route must be a list of customer numbers")
        nodes = []
        for v in route:
            if isinstance(v, bool) or not isinstance(v, (int, np.integer)):
                raise HarnessError(f"customer numbers must be integers, got {v!r}")
            nodes.append(int(v))
        if nodes:
            clean.append(nodes)
    n = instance["customers"]
    visited = [v for r in clean for v in r]
    if len(visited) != n or sorted(visited) != list(range(1, n + 1)):
        missing = n - len(set(visited) & set(range(1, n + 1)))
        extra = len([v for v in visited if not 1 <= v <= n])
        dupes = len(visited) - len(set(visited))
        raise HarnessError(f"routes must visit customers 1..{n} exactly once "
                           f"({missing} missing, {extra} out of range, {dupes} repeated)")
    demands = instance["demands"]
    for route in clean:
        load = sum(demands[v] for v in route)
        if load > instance["capacity"]:
            raise HarnessError(f"a route carries {load}, over the capacity {instance['capacity']}")
    coords = instance["coords"]
    total = 0
    for route in clean:
        previous = 0
        for node in route + [0]:
            (x1, y1), (x2, y2) = coords[previous], coords[node]
            total += nint(math.hypot(x1 - x2, y1 - y2))
            previous = node
    return total


def gap_pct(cost: int, bks: int) -> float:
    """Percentage gap of *cost* above the best-known solution."""
    return round(100.0 * (cost - bks) / bks, 4)


# ---------------------------------------------------------------- baseline: savings
def savings_routes(instance: dict) -> list[list[int]]:
    """Clarke and Wright (1964) parallel savings, then 2-opt inside each route.

    The textbook construction heuristic, used as the simple-rule baseline.
    """
    d = distance_matrix(instance["coords"])
    demands = instance["demands"]
    capacity = instance["capacity"]
    n = instance["customers"]
    route_of = list(range(n + 1))                # customer -> route id
    routes = {i: [i] for i in range(1, n + 1)}
    loads = {i: demands[i] for i in range(1, n + 1)}
    i_idx, j_idx = np.triu_indices(n, k=1)
    i_idx, j_idx = i_idx + 1, j_idx + 1
    saving = d[0, i_idx] + d[0, j_idx] - d[i_idx, j_idx]
    order = np.lexsort((j_idx, i_idx, -saving))
    for k in order:
        if saving[k] <= 0:
            break
        a, b = int(i_idx[k]), int(j_idx[k])
        ra, rb = route_of[a], route_of[b]
        if ra == rb or loads[ra] + loads[rb] > capacity:
            continue
        A, B = routes[ra], routes[rb]
        if A[-1] == a and B[0] == b:
            merged = A + B
        elif A[0] == a and B[-1] == b:
            merged = B + A
        elif A[0] == a and B[0] == b:
            merged = A[::-1] + B
        elif A[-1] == a and B[-1] == b:
            merged = A + B[::-1]
        else:
            continue                             # a or b is interior
        routes[ra] = merged
        loads[ra] += loads[rb]
        del routes[rb], loads[rb]
        for v in B:
            route_of[v] = ra
    return [two_opt(r, d) for r in routes.values()]


def two_opt(route: list[int], d: np.ndarray) -> list[int]:
    """First-improvement 2-opt on one route (depot at both ends)."""
    tour = [0] + route + [0]
    improved = True
    while improved:
        improved = False
        for i in range(1, len(tour) - 2):
            for j in range(i + 1, len(tour) - 1):
                delta = (d[tour[i - 1], tour[j]] + d[tour[i], tour[j + 1]]
                         - d[tour[i - 1], tour[i]] - d[tour[j], tour[j + 1]])
                if delta < 0:
                    tour[i:j + 1] = tour[i:j + 1][::-1]
                    improved = True
    return tour[1:-1]


# ---------------------------------------------------------------- static check
def docstring_nodes(tree: ast.AST) -> set[int]:
    """ids of the Constant nodes that are docstrings."""
    found = set()
    for node in ast.walk(tree):
        if isinstance(node, (ast.Module, ast.FunctionDef, ast.AsyncFunctionDef, ast.ClassDef)):
            body = getattr(node, "body", [])
            if (body and isinstance(body[0], ast.Expr) and isinstance(body[0].value, ast.Constant)
                    and isinstance(body[0].value.value, str)):
                found.add(id(body[0].value))
    return found


def static_check(path: Path) -> list[str]:
    """Return the reasons an experiment file is refused (empty if it is fine).

    An allowlist, read from the parsed code: only the listed modules may be
    imported; nothing that opens files, inspects the interpreter or reaches
    around the harness may be named; and the file may not carry large tables
    of numbers or text (which could smuggle in routes computed elsewhere).
    """
    raw = path.read_bytes()
    problems: list[str] = []
    if len(raw) > MAX_EXPERIMENT_BYTES:
        problems.append(f"file is {len(raw)} bytes (limit {MAX_EXPERIMENT_BYTES})")
    try:
        tree = ast.parse(raw.decode("utf-8"))
    except (SyntaxError, UnicodeDecodeError) as exc:
        return problems + [f"does not parse: {exc}"]
    docs = docstring_nodes(tree)
    numbers = 0
    string_chars = 0
    for node in ast.walk(tree):
        if isinstance(node, ast.Import):
            for alias in node.names:
                if alias.name.split(".")[0] not in ALLOWED_IMPORTS:
                    problems.append(f"import {alias.name}")
        elif isinstance(node, ast.ImportFrom):
            if node.level or (node.module or "").split(".")[0] not in ALLOWED_IMPORTS:
                problems.append(f"from {'.' * node.level}{node.module or ''} import")
            for alias in node.names:
                if alias.name in BANNED_NAMES or alias.name in BANNED_ATTRIBUTES or alias.name.startswith("__"):
                    problems.append(f"import of {alias.name}")
        elif isinstance(node, ast.Name):
            if node.id in BANNED_NAMES or (node.id.startswith("__") and node.id != "__name__"):
                problems.append(f"name {node.id}")
        elif isinstance(node, ast.Attribute):
            if node.attr in BANNED_ATTRIBUTES or node.attr.startswith("__"):
                problems.append(f"attribute .{node.attr}")
        elif isinstance(node, (ast.List, ast.Tuple, ast.Set)):
            if len(node.elts) > MAX_LITERAL_ELEMENTS:
                problems.append(f"a literal with {len(node.elts)} elements (limit {MAX_LITERAL_ELEMENTS})")
        elif isinstance(node, ast.Dict):
            if len(node.keys) > MAX_LITERAL_ELEMENTS:
                problems.append(f"a dict literal with {len(node.keys)} entries (limit {MAX_LITERAL_ELEMENTS})")
        elif isinstance(node, ast.Constant):
            if isinstance(node.value, (int, float, complex)) and not isinstance(node.value, bool):
                numbers += 1
            elif isinstance(node.value, (str, bytes)) and id(node) not in docs:
                string_chars += len(node.value)
    if numbers > MAX_NUMERIC_CONSTANTS:
        problems.append(f"{numbers} numeric constants (limit {MAX_NUMERIC_CONSTANTS})")
    if string_chars > MAX_STRING_CHARS:
        problems.append(f"{string_chars} characters of string constants (limit {MAX_STRING_CHARS})")
    return sorted(set(problems))


# ---------------------------------------------------------------- running a solver
def children_cpu() -> float:
    """CPU seconds used so far by finished child processes (0 where unmeasurable)."""
    if resource is None:
        return 0.0
    usage = resource.getrusage(resource.RUSAGE_CHILDREN)
    return usage.ru_utime + usage.ru_stime


def kill_group(proc: subprocess.Popen) -> None:
    """Kill the runner and anything it started."""
    if proc.poll() is None or os.name == "posix":
        try:
            if os.name == "posix":
                os.killpg(proc.pid, signal.SIGKILL)
            else:  # pragma: no cover - Windows
                proc.kill()
        except (ProcessLookupError, PermissionError, OSError):
            pass
    try:
        proc.wait(10)
    except subprocess.TimeoutExpired:  # pragma: no cover
        pass


def run_one(path: Path, instance: dict, seed: int) -> dict:
    """Solve one instance under the rules; return cost, gap and timings."""
    limit = time_limit(instance)
    token = secrets.token_hex(16)
    message = json.dumps({"token": token, "seed": seed, "time_limit": limit,
                          "capacity": instance["capacity"], "coords": instance["coords"],
                          "demands": instance["demands"]}).encode("utf-8")
    env = {**os.environ, "OMP_NUM_THREADS": "1", "OPENBLAS_NUM_THREADS": "1",
           "MKL_NUM_THREADS": "1", "NUMEXPR_NUM_THREADS": "1", "PYTHONHASHSEED": "0"}
    lines: queue.Queue = queue.Queue()
    prefix = token.encode("ascii") + b" "
    with tempfile.TemporaryDirectory() as tmp:
        with open(Path(tmp) / "stderr.txt", "w+b") as stderr:
            cpu_before = children_cpu()
            extra = {"start_new_session": True} if os.name == "posix" else {}
            proc = subprocess.Popen([sys.executable, "-E", str(RUNNER), str(path.resolve())],
                                    stdin=subprocess.PIPE, stdout=subprocess.PIPE, stderr=stderr,
                                    cwd=tmp, env=env, **extra)

            def reader() -> None:
                assert proc.stdout is not None
                for raw in proc.stdout:
                    if raw.startswith(prefix):
                        kind, _, payload = raw[len(prefix):].decode("utf-8", "replace").partition(" ")
                        lines.put((time.monotonic(), kind.strip(), payload))
                lines.put((time.monotonic(), "EOF", ""))

            threading.Thread(target=reader, daemon=True).start()
            try:
                assert proc.stdin is not None
                proc.stdin.write(message)
                proc.stdin.close()
                ready_at = wait_for(lines, ("READY",), READY_TIMEOUT_S, instance["name"], stderr)
                deadline = limit * TIME_FACTOR + TIME_GRACE_S + KILL_EXTRA_S
                done_at, payload = wait_for(lines, ("RESULT",), deadline, instance["name"], stderr,
                                            with_payload=True)
            finally:
                kill_group(proc)
            cpu = children_cpu() - cpu_before
    elapsed = done_at - ready_at
    if elapsed > limit * TIME_FACTOR + TIME_GRACE_S:
        raise HarnessError(f"{instance['name']}: solve() answered after {elapsed:.2f} s, over its "
                           f"{limit} s limit (allowed {limit * TIME_FACTOR + TIME_GRACE_S:.2f} s).")
    if resource is not None and cpu > limit * CPU_FACTOR + CPU_GRACE_S:
        raise HarnessError(f"{instance['name']}: used {cpu:.1f} CPU seconds for a {limit} s limit; "
                           "experiments must use one core.")
    try:
        routes = json.loads(payload)
    except ValueError as exc:
        raise HarnessError(f"{instance['name']}: the answer could not be read ({exc}).") from exc
    cost = check_solution(instance, routes)
    return {"instance": instance["name"], "customers": instance["customers"], "seed": seed,
            "time_limit": limit, "cost": cost, "bks": instance["bks"],
            "gap_pct": gap_pct(cost, instance["bks"]), "routes": len([r for r in routes if r]),
            "solve_seconds": round(elapsed, 2), "cpu_seconds": round(cpu, 2), "solution": routes}


def wait_for(lines: queue.Queue, kinds: tuple[str, ...], timeout: float, name: str, stderr,
             with_payload: bool = False):
    """Wait for a protocol line of one of *kinds*; explain anything else."""
    end = time.monotonic() + timeout
    while True:
        remaining = end - time.monotonic()
        if remaining <= 0:
            raise HarnessError(f"{name}: no answer within {timeout:.1f} s; the run was stopped.")
        try:
            stamp, kind, payload = lines.get(timeout=remaining)
        except queue.Empty:
            continue
        if kind in kinds:
            return (stamp, payload) if with_payload else stamp
        if kind == "ERROR":
            try:
                detail = json.loads(payload)
            except ValueError:
                detail = payload
            raise HarnessError(f"{name}: solve() raised an error:\n{detail}")
        if kind == "EOF":
            stderr.seek(0)
            tail = stderr.read()[-1500:].decode("utf-8", "replace")
            raise HarnessError(f"{name}: the solver process ended without an answer.\n{tail}")


def run_set(path: Path, names: list[str], instances: dict[str, dict], seeds: list[int]) -> list[dict]:
    """Run *path* on every instance in *names* for every seed (caller holds the lock)."""
    results = []
    for seed in seeds:
        for name in names:
            result = run_one(path, instances[name], seed)
            results.append(result)
            print(f"  {name:14s} seed {seed}  cost {result['cost']:>8d}  "
                  f"gap {result['gap_pct']:6.3f}%  ({result['solve_seconds']} s)", flush=True)
    return results


@contextlib.contextmanager
def solver_lock():
    """Run one timed evaluation at a time, so parallel trials never share the CPU.

    The time limit is wall-clock time, so two solvers running at once would
    each get less computing and score worse. Other evaluations wait here.
    Budget checks and ledger writes also happen under this lock.
    """
    RUNS_DIR.mkdir(parents=True, exist_ok=True)
    if fcntl is None:  # Windows: a local check only; the lab itself runs on Linux.
        yield
        return
    with open(LOCK, "w") as handle:
        try:
            fcntl.flock(handle, fcntl.LOCK_EX | fcntl.LOCK_NB)
        except BlockingIOError:
            print("Another evaluation is running; waiting for it to finish ...", flush=True)
            fcntl.flock(handle, fcntl.LOCK_EX)
        try:
            yield
        finally:
            fcntl.flock(handle, fcntl.LOCK_UN)


def summarize(results: list[dict], reference: dict[tuple[str, int], int] | None = None) -> dict:
    """Mean, median and worst gap; how many instances beat the reference cost."""
    if not results:
        raise HarnessError("no instances were run")
    gaps = [r["gap_pct"] for r in results]
    out = {
        "instances": len(results),
        "mean_gap_pct": round(statistics.fmean(gaps), 4),
        "median_gap_pct": round(statistics.median(gaps), 4),
        "worst_gap_pct": round(max(gaps), 4),
        "seconds": round(sum(r["solve_seconds"] for r in results), 1),
        "cpu_seconds": round(sum(r["cpu_seconds"] for r in results), 1),
    }
    if reference:
        compared = [r for r in results if (r["instance"], r["seed"]) in reference]
        wins = sum(1 for r in compared if r["cost"] < reference[(r["instance"], r["seed"])])
        if compared:
            out["beats_reference"] = f"{wins}/{len(compared)}"
    return out


# ---------------------------------------------------------------- ledger
def git_commit() -> str:
    """Return the short git commit of the repository, or '' if unavailable."""
    try:
        out = subprocess.run(["git", "-C", str(REPO_ROOT), "rev-parse", "--short", "HEAD"],
                             capture_output=True, text=True, timeout=10)
        return out.stdout.strip()
    except (OSError, subprocess.SubprocessError):
        return ""


def read_ledger() -> list[dict[str, str]]:
    """Return the ledger rows (empty if there is no ledger yet)."""
    if not LEDGER.exists():
        return []
    with open(LEDGER, encoding="utf-8", newline="") as handle:
        return list(csv.DictReader(handle, delimiter="\t"))


def append_ledger(row: dict[str, object]) -> None:
    """Append one row to the ledger, writing the header the first time."""
    RUNS_DIR.mkdir(parents=True, exist_ok=True)
    new = not LEDGER.exists()
    with open(LEDGER, "a", encoding="utf-8", newline="") as handle:
        writer = csv.DictWriter(handle, fieldnames=LEDGER_FIELDS, delimiter="\t", extrasaction="ignore")
        if new:
            writer.writeheader()
        writer.writerow({k: str(row.get(k, "")).replace("\t", " ").replace("\n", " ")
                         for k in LEDGER_FIELDS})


def save_details(row: dict, results: list[dict]) -> None:
    """Keep every instance's result and routes, so any number can be re-checked."""
    DETAILS_DIR.mkdir(parents=True, exist_ok=True)
    stem = (f"{row['utc'].replace(':', '')}_{row['kind']}_{Path(str(row['experiment'])).stem}"
            f"_{row.get('experiment_sha12') or 'none'}_{uuid.uuid4().hex[:8]}")
    with open(DETAILS_DIR / f"{stem}.json", "x", encoding="utf-8") as handle:
        handle.write(json.dumps({"row": row, "results": results}) + "\n")


def relative(path: Path) -> str:
    """Show *path* relative to the repository root when possible."""
    try:
        return str(path.resolve().relative_to(REPO_ROOT))
    except ValueError:
        return str(path)


def base_row(kind: str, split: str, path: Path | None, seeds: list[int], note: str) -> dict:
    """Fields shared by every ledger row."""
    prints = fingerprint()
    return {
        "utc": datetime.now(timezone.utc).strftime("%Y-%m-%dT%H:%M:%SZ"),
        "kind": kind, "split": split,
        "experiment": relative(path) if path else "savings (in harness)",
        "experiment_sha12": sha256_file(path)[:12] if path else "",
        "git_commit": git_commit(), "seeds": ",".join(map(str, seeds)),
        "harness_sha12": prints["harness"][:12], "snapshot_sha12": prints["snapshot"][:12],
        "note": note,
    }


def reference_costs(split: str) -> dict[tuple[str, int], int]:
    """Costs of the frozen reference per (instance, seed), from saved details."""
    costs: dict[tuple[str, int], int] = {}
    if not DETAILS_DIR.exists():
        return costs
    reference_path = relative(REFERENCE)
    reference_sha = sha256_file(REFERENCE)[:12]
    for path in sorted(DETAILS_DIR.glob("*.json")):
        record = json.loads(path.read_text(encoding="utf-8"))
        row = record["row"]
        if (row.get("split") == split and row.get("kind") in ("baseline", "final_reference")
                and row.get("experiment") == reference_path
                and row.get("experiment_sha12") == reference_sha and row.get("status") == "ok"):
            for r in record["results"]:
                costs[(r["instance"], r["seed"])] = r["cost"]
    return costs


def started(kind: str) -> int:
    """How many val evaluations of *kind* this ledger has started (the budget count)."""
    return sum(1 for r in read_ledger()
               if r["kind"] == kind and r["split"] == "val" and r["status"] == "started")


def evaluate(path: Path, split: str, kind: str, seeds: list[int], note: str,
             names: list[str] | None = None, budget: int | None = None) -> tuple[dict, list[dict]]:
    """Run an experiment on a split under the lock and record it in the ledger."""
    if not path.exists():
        raise HarnessError(f"No experiment file at {path}")
    problems = static_check(path)
    if problems:
        row = base_row(kind, split, path, seeds, note)
        row.update(status="refused", note=f"{note} | refused: {'; '.join(problems)}"[:500])
        with solver_lock():
            append_ledger(row)
        raise HarnessError("The experiment is refused: " + "; ".join(problems) + ". Experiments may "
                           "import only " + ", ".join(sorted(ALLOWED_IMPORTS)) + ", must not open "
                           "files or inspect the interpreter, and must not carry large tables.")
    instances = load_instances()
    names = names or split_names(instances, split)
    if not names:
        raise HarnessError("no instances to run")
    with solver_lock():
        if budget is not None and started(kind) >= budget:
            raise HarnessError(f"The {kind} budget of {budget} is used up.")
        row = base_row(kind, split, path, seeds, note)
        append_ledger({**row, "status": "started"})
        try:
            results = run_set(path, names, instances, seeds)
        except HarnessError as exc:
            row.update(status="invalid", note=f"{note} | {exc}"[:500])
            append_ledger(row)
            raise
        row.update(summarize(results, reference_costs(split)))
        row["status"] = "ok"
        append_ledger(row)
        save_details(row, results)
    return row, results


def savings_on(split: str) -> tuple[dict, list[dict]]:
    """Score the savings baseline on a split (deterministic, no time limit needed)."""
    instances = load_instances()
    results = []
    for name in split_names(instances, split):
        started_at = time.time()
        routes = savings_routes(instances[name])
        cost = check_solution(instances[name], routes)
        results.append({"instance": name, "customers": instances[name]["customers"], "seed": 0,
                        "cost": cost, "bks": instances[name]["bks"],
                        "gap_pct": gap_pct(cost, instances[name]["bks"]), "routes": len(routes),
                        "solve_seconds": round(time.time() - started_at, 2), "cpu_seconds": 0.0,
                        "solution": routes})
    return summarize(results), results


def parse_seeds(text: str) -> list[int]:
    """Parse a comma-separated list of seeds."""
    try:
        seeds = [int(s) for s in text.split(",") if s.strip()]
    except ValueError as exc:
        raise HarnessError(f"seeds must be whole numbers separated by commas, got {text!r}") from exc
    if not seeds or len(seeds) != len(set(seeds)) or any(s < 0 for s in seeds):
        raise HarnessError(f"give one or more distinct, non-negative seeds, got {text!r}")
    return seeds


# ---------------------------------------------------------------- commands
def best_val_gap() -> float | None:
    """Best (lowest) seed-0 val mean gap among valid experiments and baselines."""
    values = [float(r["mean_gap_pct"]) for r in read_ledger()
              if r["split"] == "val" and r["status"] == "ok" and r["mean_gap_pct"]
              and r["seeds"] == "0" and r["kind"] in ("experiment", "baseline")]
    return min(values) if values else None


def cmd_fingerprint(_: argparse.Namespace) -> int:
    print(json.dumps(fingerprint(), indent=2))
    return 0


def cmd_describe(_: argparse.Namespace) -> int:
    instances = load_instances()
    info = {
        "question": "Within 3 s per 100 customers on one core, get as close as possible to the "
                    "CVRPLIB X best-known solutions; beat PyVRP's default solver.",
        "metric": "mean gap to BKS (%) over val, seed 0; lower is better",
        "splits": {s: [f"{n} ({instances[n]['customers']} customers, {time_limit(instances[n])} s)"
                       for n in split_names(instances, s)]
                   for s in ("val", "test", "scale")},
        "train_instances": split_names(instances, "train"),
        "hunt_instances": split_names(instances, "hunt"),
        "val_seconds_per_evaluation": round(sum(time_limit(instances[n])
                                                for n in split_names(instances, "val")), 1),
        "solve_signature": "solve(instance, time_limit, seed) -> list of routes (customer numbers 1..n)",
        "instance_keys": ["capacity", "coords", "demands", "distance"],
        "allowed_imports": sorted(ALLOWED_IMPORTS),
        "experiment_budget": EXPERIMENT_BUDGET,
        "experiments_used": started("experiment"),
        "recheck_budget": RECHECK_BUDGET,
        "rechecks_used": started("recheck"),
        "recheck_seeds": list(RECHECK_SEEDS),
        "best_val_mean_gap_pct": best_val_gap(),
        "final_done": final_done(),
    }
    print(json.dumps(info, indent=2))
    return 0


def cmd_baselines(_: argparse.Namespace) -> int:
    """Score the savings rule and the frozen PyVRP reference on val (seed 0)."""
    out = {}
    print("Savings baseline (Clarke-Wright + 2-opt) on val:")
    summary, results = savings_on("val")
    row = base_row("baseline", "val", None, [0], "reference baseline savings")
    row.update(summary, status="ok")
    with solver_lock():
        append_ledger(row)
        save_details(row, results)
    out["savings"] = summary
    print(json.dumps(summary))
    print("PyVRP default (frozen reference.py) on val:")
    row, _ = evaluate(REFERENCE, "val", "baseline", [SEED], "reference baseline pyvrp_default")
    out["pyvrp_default"] = {k: row[k] for k in ("mean_gap_pct", "median_gap_pct", "worst_gap_pct")}
    print(json.dumps(out, indent=2))
    return 0


def cmd_probe(args: argparse.Namespace) -> int:
    """Free runs on train or hunt instances; not counted, not used for decisions."""
    instances = load_instances()
    names = [n.strip() for n in args.instances.split(",") if n.strip()]
    if not names:
        raise HarnessError("name at least one train or hunt instance with --instances")
    for name in names:
        if name not in instances:
            raise HarnessError(f"Unknown instance {name}")
        if instances[name]["split"] not in ("train", "hunt"):
            raise HarnessError(f"{name} is in the {instances[name]['split']} split; probe only "
                               "train or hunt instances.")
    seeds = parse_seeds(args.seeds)
    if len(seeds) > MAX_PROBE_SEEDS:
        raise HarnessError(f"probe at most {MAX_PROBE_SEEDS} seeds at a time")
    row, _ = evaluate(Path(args.experiment).resolve(), "probe", "probe", seeds, args.note or "", names=names)
    print("PROBE " + json.dumps(row))
    return 0


def cmd_evaluate(args: argparse.Namespace) -> int:
    best = best_val_gap()
    row, _ = evaluate(Path(args.experiment).resolve(), "val", "experiment", [SEED], args.note or "",
                      budget=EXPERIMENT_BUDGET)
    row["best_previous_mean_gap_pct"] = best
    row["experiments_used"] = started("experiment")
    print("RESULT " + json.dumps(row))
    return 0


def cmd_recheck(args: argparse.Namespace) -> int:
    """Re-run on val with seeds 1 and 2, for the Skeptic (and the reference, once, if needed)."""
    path = Path(args.experiment).resolve()
    sha = sha256_file(path)[:12]
    evaluated = any(r["kind"] == "experiment" and r["split"] == "val" and r["status"] == "ok"
                    and r["experiment_sha12"] == sha for r in read_ledger())
    if not evaluated:
        raise HarnessError("Recheck only a file that `evaluate` has already scored (same contents).")
    seeds = list(RECHECK_SEEDS)
    instances = load_instances()
    ref = reference_costs("val")
    if not all((n, s) in ref for n in split_names(instances, "val") for s in seeds):
        print("Running the frozen reference on the recheck seeds first (once per ledger, not counted):")
        evaluate(REFERENCE, "val", "baseline", seeds, "reference pyvrp_default on recheck seeds")
    row, _ = evaluate(path, "val", "recheck", seeds, args.note or "", budget=RECHECK_BUDGET)
    row["rechecks_used"] = started("recheck")
    print("RECHECK " + json.dumps(row))
    return 0


def paired_stats(experiment: list[dict], reference: list[dict]) -> dict:
    """Paired comparison of the experiment with the reference on the same problems and seeds.

    For each problem the gap is averaged over the seeds, then d = experiment gap
    minus reference gap (percentage points; negative means the experiment is
    better). Reported: mean d with a 95 percent bootstrap interval over problems
    (fixed random seed, so the numbers are reproducible), problems won and lost,
    an exact two-sided sign test on those wins and losses, and the head-to-head
    count over every (problem, seed) pair.
    """
    ref = {(r["instance"], r["seed"]): r for r in reference}
    per_problem: dict[str, list[float]] = {}
    pair_wins = pair_losses = pair_ties = 0
    for r in experiment:
        other = ref.get((r["instance"], r["seed"]))
        if other is None:
            continue
        per_problem.setdefault(r["instance"], []).append(r["gap_pct"] - other["gap_pct"])
        pair_wins += r["cost"] < other["cost"]
        pair_losses += r["cost"] > other["cost"]
        pair_ties += r["cost"] == other["cost"]
    diffs = np.array([statistics.fmean(v) for v in per_problem.values()])
    if not len(diffs):
        raise HarnessError("no paired results to compare")
    rng = np.random.default_rng(0)
    boots = rng.choice(diffs, size=(BOOTSTRAP_DRAWS, len(diffs)), replace=True).mean(axis=1)
    wins, losses = int((diffs < 0).sum()), int((diffs > 0).sum())
    n = wins + losses
    tail = sum(math.comb(n, k) for k in range(0, min(wins, losses) + 1)) / 2 ** n if n else 1.0
    return {
        "problems": len(diffs),
        "seeds": sorted({r["seed"] for r in experiment}),
        "mean_difference_pct_points": round(float(diffs.mean()), 4),
        "ci95_low": round(float(np.percentile(boots, 2.5)), 4),
        "ci95_high": round(float(np.percentile(boots, 97.5)), 4),
        "problems_won": wins, "problems_lost": losses, "problems_tied": len(diffs) - n,
        "sign_test_p_two_sided": round(min(1.0, 2 * tail), 5),
        "pairs_won": pair_wins, "pairs_lost": pair_losses, "pairs_tied": pair_ties,
    }


def cmd_final(args: argparse.Namespace) -> int:
    path = Path(args.experiment).resolve()
    if path != DEFAULT_EXPERIMENT.resolve():
        raise HarnessError("`final` scores lab/cvrp/experiment.py, the promoted solver, and nothing else.")
    RUNS_DIR.mkdir(parents=True, exist_ok=True)
    try:
        # Created before anything runs: an interrupted final still counts as used.
        with open(FINAL_STARTED, "x", encoding="utf-8") as handle:
            handle.write(json.dumps({"utc": datetime.now(timezone.utc).isoformat(),
                                     "experiment_sha256": sha256_file(path)}) + "\n")
    except FileExistsError:
        raise HarnessError(f"The held-out splits were already used ({relative(FINAL_STARTED)}). "
                           "The final score is reported once; it is never re-run to get a "
                           "better number.") from None
    result: dict[str, object] = {"fingerprint": fingerprint(),
                                 "experiment_sha256": sha256_file(path),
                                 "definitions": {"seconds_per_100_customers": SECONDS_PER_100_CUSTOMERS,
                                                 "seeds": list(FINAL_SEEDS)}}
    seeds = list(FINAL_SEEDS)
    pooled_exp: list[dict] = []
    pooled_ref: list[dict] = []
    for split in ("test", "scale"):
        print(f"Reference (PyVRP default) on {split}, seeds {seeds}:")
        ref_row, ref_results = evaluate(REFERENCE, split, "final_reference", seeds,
                                        f"final reference on {split}")
        print(f"Experiment on {split}, seeds {seeds}:")
        exp_row, exp_results = evaluate(path, split, "final", seeds, args.note or f"final on {split}")
        savings, _ = savings_on(split)
        result[split] = {"experiment": exp_row, "pyvrp_default": ref_row, "savings": savings,
                         "paired_vs_pyvrp_default": paired_stats(exp_results, ref_results)}
        pooled_exp += exp_results
        pooled_ref += ref_results
    result["test_and_scale_pooled"] = {"paired_vs_pyvrp_default": paired_stats(pooled_exp, pooled_ref)}
    FINAL_RESULT.write_text(json.dumps(result, indent=2) + "\n", encoding="utf-8")
    print("FINAL " + json.dumps(result))
    return 0


def parse_solution_file(path: Path) -> list[list[int]]:
    """Read a CVRPLIB-format solution file ("Route #1: 3 7 9 ...")."""
    routes = []
    for number, raw in enumerate(path.read_text(encoding="utf-8").splitlines(), start=1):
        line = raw.strip()
        if line.lower().startswith("route"):
            try:
                routes.append([int(x) for x in line.partition(":")[2].split()])
            except ValueError as exc:
                raise HarnessError(f"{path.name} line {number}: {exc}") from exc
    if not routes:
        raise HarnessError(f"{path} contains no 'Route #k:' lines")
    return routes


def cmd_verify(args: argparse.Namespace) -> int:
    """Check a solution file and compare it with the snapshot's BKS."""
    instances = load_instances()
    if args.instance not in instances:
        raise HarnessError(f"Unknown instance {args.instance}")
    instance = instances[args.instance]
    if instance["split"] in ("val", "test", "scale") and not final_done():
        raise HarnessError(f"{args.instance} is in the {instance['split']} split; verify it only after `final`.")
    path = Path(args.solution).resolve()
    cost = check_solution(instance, parse_solution_file(path))
    verdict = ("BEATS the best-known solution in the snapshot" if cost < instance["bks"]
               else "equals the best-known solution" if cost == instance["bks"]
               else "is above the best-known solution")
    out = {"instance": args.instance, "cost": cost, "bks_in_snapshot": instance["bks"],
           "gap_pct": gap_pct(cost, instance["bks"]), "verdict": verdict,
           "solution_sha12": sha256_file(path)[:12], "solution_file": relative(path)}
    with solver_lock():
        new = not RECORDS.exists()
        with open(RECORDS, "a", encoding="utf-8", newline="") as handle:
            writer = csv.DictWriter(handle, fieldnames=["utc", *out.keys()], delimiter="\t")
            if new:
                writer.writeheader()
            writer.writerow({"utc": datetime.now(timezone.utc).strftime("%Y-%m-%dT%H:%M:%SZ"), **out})
    print("VERIFY " + json.dumps(out))
    if cost < instance["bks"]:
        print("A possible new record. Before claiming it, check the current CVRPLIB table "
              "(galgos.inf.puc-rio.br/cvrplib), because the snapshot's BKS may be out of date.")
    return 0


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(description="Artemis routing harness (frozen).")
    sub = parser.add_subparsers(dest="command", required=True)
    sub.add_parser("fingerprint", help="SHA-256 of harness, runner, reference and snapshot")
    sub.add_parser("describe", help="the task, splits, time limits and budgets")
    sub.add_parser("baselines", help="score the savings rule and PyVRP default on val")
    p = sub.add_parser("probe", help="free runs on train or hunt instances")
    p.add_argument("--experiment", default=str(DEFAULT_EXPERIMENT))
    p.add_argument("--instances", required=True, help="comma-separated train or hunt instance names")
    p.add_argument("--seeds", default="0")
    p.add_argument("--note", default="")
    p = sub.add_parser("evaluate", help="score one experiment on val (counts toward the budget)")
    p.add_argument("--experiment", default=str(DEFAULT_EXPERIMENT))
    p.add_argument("--note", default="")
    p = sub.add_parser("recheck", help="re-run an evaluated file on val with seeds 1 and 2 (Skeptic)")
    p.add_argument("--experiment", default=str(DEFAULT_EXPERIMENT))
    p.add_argument("--note", default="")
    p = sub.add_parser("final", help="score lab/cvrp/experiment.py on test and scale, once")
    p.add_argument("--experiment", default=str(DEFAULT_EXPERIMENT))
    p.add_argument("--note", default="")
    p = sub.add_parser("verify", help="check a CVRPLIB-format solution file against the BKS")
    p.add_argument("--instance", required=True)
    p.add_argument("--solution", required=True)
    args = parser.parse_args(argv)
    handlers = {"fingerprint": cmd_fingerprint, "describe": cmd_describe, "baselines": cmd_baselines,
                "probe": cmd_probe, "evaluate": cmd_evaluate, "recheck": cmd_recheck,
                "final": cmd_final, "verify": cmd_verify}
    try:
        return handlers[args.command](args)
    except HarnessError as exc:
        print(f"HARNESS: {exc}")
        return 1


if __name__ == "__main__":
    sys.exit(main())
