"""Frozen reference solver: PyVRP 0.14.0 with its default settings.

DO NOT EDIT THIS FILE. It is part of the harness fingerprint. It is the
"state-of-the-art library default" baseline that every experiment is compared
with: the same solver anyone gets with `pip install pyvrp`, given the same
time limit and seed as the experiment.

The starting lab/cvrp/experiment.py is a copy of this file; agents improve
the copy, never this one.
"""

from __future__ import annotations

import numpy as np
from pyvrp import Client, Depot, Location, ProblemData, VehicleType, solve as pyvrp_solve
from pyvrp.stop import MaxRuntime


def build_data(instance: dict) -> ProblemData:
    """Turn the harness's instance dictionary into PyVRP problem data."""
    coords = instance["coords"]
    demands = instance["demands"]
    distance = np.asarray(instance["distance"], dtype=np.int64)
    customers = len(demands) - 1
    locations = [Location(x=int(x), y=int(y)) for x, y in coords]
    clients = [Client(location=i, delivery=[int(demands[i])]) for i in range(1, customers + 1)]
    vehicles = [VehicleType(num_available=customers, capacity=[int(instance["capacity"])])]
    return ProblemData(locations=locations, clients=clients, depots=[Depot(location=0)],
                       vehicle_types=vehicles, distance_matrices=[distance],
                       duration_matrices=[np.zeros_like(distance)])


def solve(instance: dict, time_limit: float, seed: int) -> list[list[int]]:
    """Return routes as lists of customer indices (1..n); the depot is 0."""
    data = build_data(instance)
    result = pyvrp_solve(data, stop=MaxRuntime(time_limit), seed=seed, display=False)
    location = [client.location for client in data.clients()]
    return [[int(location[a.idx]) for a in route if a.is_client()]
            for route in result.best.routes()]
