"""Frozen runner: executes one experiment's solve() in a clean process.

DO NOT EDIT THIS FILE. It is part of the harness fingerprint.

The harness starts this script with `python -E` (PYTHON* variables ignored),
in a new process group, from an empty temporary folder; the script removes
its own folder from the import path, so an experiment cannot import the
harness. It reads one JSON
message on stdin (the instance, the time limit, the seed and a one-time
token), builds the instance view, imports the experiment from its path, prints
"<token> READY", calls solve(), and prints "<token> RESULT <routes as JSON>".
The harness, not this process, measures the time between those two lines.
The token keeps anything the experiment prints from being mistaken for a
protocol line.
"""

import importlib.util
import json
import random
import sys
import traceback
from pathlib import Path

import numpy as np


def distance_matrix(coords):
    """Rounded Euclidean distances (CVRPLIB convention), same as the harness."""
    xy = np.asarray(coords, dtype=np.float64)
    diff = xy[:, None, :] - xy[None, :, :]
    return np.floor(np.sqrt((diff ** 2).sum(axis=2)) + 0.5).astype(np.int64)


def main():
    here = str(Path(__file__).resolve().parent)
    sys.path[:] = [p for p in sys.path if p not in ("", ".", here)]
    message = json.loads(sys.stdin.read())
    token = message["token"]
    out = sys.stdout

    def emit(kind, payload=""):
        out.write(f"{token} {kind} {payload}\n")
        out.flush()

    try:
        view = {
            "capacity": int(message["capacity"]),
            "coords": np.asarray(message["coords"], dtype=np.int64),
            "demands": np.asarray(message["demands"], dtype=np.int64),
            "distance": distance_matrix(message["coords"]),
        }
        seed = int(message["seed"])
        limit = float(message["time_limit"])
        random.seed(seed)
        np.random.seed(seed)
        spec = importlib.util.spec_from_file_location("artemis_experiment", sys.argv[1])
        module = importlib.util.module_from_spec(spec)
        spec.loader.exec_module(module)
        if not hasattr(module, "solve"):
            raise RuntimeError("the experiment must define solve(instance, time_limit, seed)")
        emit("READY")
        routes = module.solve(view, limit, seed)
        clean = [[int(v) if isinstance(v, (int, np.integer)) and not isinstance(v, bool)
                  else repr(v) for v in route] for route in routes]
        emit("RESULT", json.dumps(clean))
    except BaseException:  # noqa: BLE001 - report every failure to the harness
        emit("ERROR", json.dumps(traceback.format_exc(limit=6)))


if __name__ == "__main__":
    main()
