"""Create and distribute the secrets Artemis Phase 1 needs.

Run everything from the repository root on your own computer, so secret
values are generated locally and never pass through chat, email, or git.

    python scripts/make_secrets.py init     # create .env with generated secrets
    # ...then open .env and paste in the four values marked FILL_ME_IN...
    python scripts/make_secrets.py check    # validate .env without printing secrets
    python scripts/make_secrets.py modal    # push the two Modal secrets
    python scripts/make_secrets.py vercel   # show what to paste into Vercel

What each subcommand does:

``init``
    Writes ``.env`` (git-ignored). Generates the Omnigent cookie secret, the
    first admin password, the machine client secret and its server-side
    HMAC digest, and a website access code. Existing values are never
    overwritten, so ``init`` is safe to re-run.

``check``
    Confirms every required value is present and well formed, and that the
    machine client digest matches the cookie secret.

``modal``
    Runs ``modal secret create --force`` for ``artemis-omnigent-deploy``
    (read by the Omnigent server) and ``artemis-llm`` (injected only into
    agent sandboxes). Values are passed as process arguments to the Modal
    CLI on your machine and are not echoed.

``vercel``
    Prints the four variables to add under Vercel, Project Settings,
    Environment Variables. Two of them are secrets; copy them straight
    from your terminal into the Vercel dashboard.
"""

from __future__ import annotations

import argparse
import hashlib
import hmac
import re
import secrets
import shutil
import subprocess
import sys
from pathlib import Path

ENV_PATH = Path(__file__).resolve().parent.parent / ".env"
PLACEHOLDER = "FILL_ME_IN"

# Default public URL of the Omnigent server on Modal. Modal web endpoints
# follow https://<workspace>--<app>-<function>.modal.run; the workspace is
# "alessoh", the app is "artemis-omnigent" and the function is "server".
DEFAULT_OMNIGENT_URL = "https://alessoh--artemis-omnigent-server.modal.run"
MACHINE_CLIENT_ID = "artemis-relay"
MACHINE_SUB = "artemis-relay"

# Values the server's Modal secret needs, in order.
DEPLOY_KEYS = [
    "DATABASE_URL",
    "OMNIGENT_ACCOUNTS_COOKIE_SECRET",
    "OMNIGENT_ACCOUNTS_BASE_URL",
    "OMNIGENT_ACCOUNTS_INIT_ADMIN_USERNAME",
    "OMNIGENT_ACCOUNTS_INIT_ADMIN_PASSWORD",
    "OMNIGENT_MACHINE_CLIENT_ID",
    "OMNIGENT_MACHINE_CLIENT_SECRET_HASH",
    "OMNIGENT_MACHINE_SUB",
    "MODAL_TOKEN_ID",
    "MODAL_TOKEN_SECRET",
]
# Values injected into agent sandboxes only.
LLM_KEYS = ["OMNIGENT_ANTHROPIC_API_KEY"]
# Values the Vercel relay needs.
VERCEL_KEYS = [
    "OMNIGENT_URL",
    "OMNIGENT_MACHINE_CLIENT_ID",
    "OMNIGENT_MACHINE_CLIENT_SECRET",
    "ARTEMIS_ACCESS_CODE",
]
VERCEL_SECRET_KEYS = {"OMNIGENT_MACHINE_CLIENT_SECRET", "ARTEMIS_ACCESS_CODE"}

ENV_TEMPLATE = """\
# Artemis secrets. This file is git-ignored. Never commit it or paste it into chat.
# Generated by scripts/make_secrets.py init. Fill in every FILL_ME_IN value.

# ---- Omnigent server (Modal secret: artemis-omnigent-deploy) ----
# Postgres connection string from Neon (https://pg.new or Vercel > Storage > Neon).
DATABASE_URL={DATABASE_URL}
# 32 random bytes as hex; signs Omnigent login cookies and machine tokens.
OMNIGENT_ACCOUNTS_COOKIE_SECRET={OMNIGENT_ACCOUNTS_COOKIE_SECRET}
# The Omnigent server's public URL on Modal (printed by `modal deploy`).
OMNIGENT_ACCOUNTS_BASE_URL={OMNIGENT_ACCOUNTS_BASE_URL}
# Login for the Omnigent web UI admin account.
OMNIGENT_ACCOUNTS_INIT_ADMIN_USERNAME={OMNIGENT_ACCOUNTS_INIT_ADMIN_USERNAME}
OMNIGENT_ACCOUNTS_INIT_ADMIN_PASSWORD={OMNIGENT_ACCOUNTS_INIT_ADMIN_PASSWORD}
# Machine client used by the Vercel relay (OAuth client-credentials grant).
OMNIGENT_MACHINE_CLIENT_ID={OMNIGENT_MACHINE_CLIENT_ID}
OMNIGENT_MACHINE_CLIENT_SECRET_HASH={OMNIGENT_MACHINE_CLIENT_SECRET_HASH}
OMNIGENT_MACHINE_SUB={OMNIGENT_MACHINE_SUB}
# A Modal API token so the server can launch agent sandboxes
# (modal.com > Settings > API Tokens > New Token).
MODAL_TOKEN_ID={MODAL_TOKEN_ID}
MODAL_TOKEN_SECRET={MODAL_TOKEN_SECRET}

# ---- Agent sandboxes (Modal secret: artemis-llm) ----
# Your Anthropic API key. Only the sandboxes receive it; the server never does.
OMNIGENT_ANTHROPIC_API_KEY={OMNIGENT_ANTHROPIC_API_KEY}

# ---- Vercel relay (Vercel project environment variables) ----
OMNIGENT_URL={OMNIGENT_URL}
# Raw machine client secret; the server stores only its HMAC digest above.
OMNIGENT_MACHINE_CLIENT_SECRET={OMNIGENT_MACHINE_CLIENT_SECRET}
# Code a visitor must enter before the website will start a lab session.
ARTEMIS_ACCESS_CODE={ARTEMIS_ACCESS_CODE}
"""


def read_env(path: Path = ENV_PATH) -> dict[str, str]:
    """Parse a simple KEY=VALUE .env file, ignoring comments and blanks.

    :param path: File to read.
    :returns: Mapping of keys to values (empty if the file is absent).
    """
    values: dict[str, str] = {}
    if not path.exists():
        return values
    for raw in path.read_text(encoding="utf-8").splitlines():
        line = raw.strip()
        if not line or line.startswith("#") or "=" not in line:
            continue
        key, _, value = line.partition("=")
        values[key.strip()] = value.strip().strip('"').strip("'")
    return values


def client_secret_digest(client_secret: str, cookie_secret_hex: str) -> str:
    """Compute the digest Omnigent stores for the machine client secret.

    Matches ``omnigent.server.device_grant_store.hash_secret``: HMAC-SHA256
    keyed by the cookie secret bytes, hex encoded.

    :param client_secret: The raw client secret.
    :param cookie_secret_hex: ``OMNIGENT_ACCOUNTS_COOKIE_SECRET`` as hex.
    :returns: 64-character hex digest.
    """
    key = bytes.fromhex(cookie_secret_hex)
    return hmac.new(key, client_secret.encode("utf-8"), hashlib.sha256).hexdigest()


def is_filled(value: str | None) -> bool:
    """Return True when a value is present and not the placeholder."""
    return bool(value) and value != PLACEHOLDER


def cmd_init(_: argparse.Namespace) -> int:
    """Create or complete .env, generating secrets that are still missing."""
    current = read_env()
    values = {key: current.get(key, "") for key in set(DEPLOY_KEYS + LLM_KEYS + VERCEL_KEYS)}

    def keep_or(key: str, generated: str) -> None:
        if not is_filled(values.get(key)):
            values[key] = generated

    keep_or("OMNIGENT_ACCOUNTS_COOKIE_SECRET", secrets.token_hex(32))
    keep_or("OMNIGENT_ACCOUNTS_INIT_ADMIN_USERNAME", "admin")
    keep_or("OMNIGENT_ACCOUNTS_INIT_ADMIN_PASSWORD", secrets.token_urlsafe(18))
    keep_or("OMNIGENT_MACHINE_CLIENT_ID", MACHINE_CLIENT_ID)
    keep_or("OMNIGENT_MACHINE_SUB", MACHINE_SUB)
    keep_or("OMNIGENT_MACHINE_CLIENT_SECRET", secrets.token_urlsafe(32))
    keep_or("ARTEMIS_ACCESS_CODE", secrets.token_urlsafe(9))
    keep_or("OMNIGENT_ACCOUNTS_BASE_URL", DEFAULT_OMNIGENT_URL)
    keep_or("OMNIGENT_URL", values["OMNIGENT_ACCOUNTS_BASE_URL"])
    # The digest always follows the current cookie secret and client secret.
    values["OMNIGENT_MACHINE_CLIENT_SECRET_HASH"] = client_secret_digest(
        values["OMNIGENT_MACHINE_CLIENT_SECRET"], values["OMNIGENT_ACCOUNTS_COOKIE_SECRET"]
    )
    for key in ("DATABASE_URL", "MODAL_TOKEN_ID", "MODAL_TOKEN_SECRET", "OMNIGENT_ANTHROPIC_API_KEY"):
        keep_or(key, PLACEHOLDER)

    ENV_PATH.write_text(ENV_TEMPLATE.format(**values), encoding="utf-8")
    try:
        ENV_PATH.chmod(0o600)
    except OSError:
        pass
    todo = [k for k, v in values.items() if v == PLACEHOLDER]
    print(f"Wrote {ENV_PATH}")
    if todo:
        print("Open .env and fill in: " + ", ".join(sorted(todo)))
    else:
        print("All values present. Next: python scripts/make_secrets.py check")
    return 0


def validate(values: dict[str, str]) -> list[str]:
    """Return a list of human-readable problems with the .env values."""
    problems: list[str] = []
    for key in DEPLOY_KEYS + LLM_KEYS + VERCEL_KEYS:
        if not is_filled(values.get(key)):
            problems.append(f"{key} is missing")
    if problems:
        return problems
    if not re.fullmatch(r"[0-9a-f]{64,}", values["OMNIGENT_ACCOUNTS_COOKIE_SECRET"]):
        problems.append("OMNIGENT_ACCOUNTS_COOKIE_SECRET must be at least 64 lowercase hex characters")
    else:
        expected = client_secret_digest(
            values["OMNIGENT_MACHINE_CLIENT_SECRET"], values["OMNIGENT_ACCOUNTS_COOKIE_SECRET"]
        )
        if not hmac.compare_digest(expected, values["OMNIGENT_MACHINE_CLIENT_SECRET_HASH"]):
            problems.append("OMNIGENT_MACHINE_CLIENT_SECRET_HASH does not match; re-run init")
    if not values["DATABASE_URL"].startswith(("postgres://", "postgresql://", "postgresql+psycopg://")):
        problems.append("DATABASE_URL should start with postgres:// or postgresql://")
    for key in ("OMNIGENT_ACCOUNTS_BASE_URL", "OMNIGENT_URL"):
        if not values[key].startswith("https://"):
            problems.append(f"{key} must start with https://")
    if values["OMNIGENT_URL"].rstrip("/") != values["OMNIGENT_ACCOUNTS_BASE_URL"].rstrip("/"):
        problems.append("OMNIGENT_URL and OMNIGENT_ACCOUNTS_BASE_URL should be the same URL")
    if not values["OMNIGENT_ANTHROPIC_API_KEY"].startswith("sk-ant-"):
        problems.append("OMNIGENT_ANTHROPIC_API_KEY does not look like an Anthropic key (sk-ant-...)")
    if values["OMNIGENT_MACHINE_SUB"] in {"admin", "local", "public", values["OMNIGENT_ACCOUNTS_INIT_ADMIN_USERNAME"]}:
        problems.append("OMNIGENT_MACHINE_SUB must be a distinct, non-admin name")
    return problems


def cmd_check(_: argparse.Namespace) -> int:
    """Validate .env and report problems without printing any secret."""
    values = read_env()
    if not values:
        print("No .env found. Run: python scripts/make_secrets.py init")
        return 1
    problems = validate(values)
    if problems:
        print("Problems found in .env:")
        for problem in problems:
            print(f"  - {problem}")
        return 1
    print(".env looks complete and consistent.")
    return 0


def run_modal_secret(name: str, pairs: dict[str, str]) -> None:
    """Create or replace one Modal secret using the Modal CLI.

    :param name: Secret name.
    :param pairs: Key/value pairs to store.
    :raises SystemExit: If the Modal CLI is missing or the command fails.
    """
    modal_cli = shutil.which("modal")
    if modal_cli is None:
        sys.exit("The Modal CLI is not installed. Run: pip install modal && modal setup")
    args = [modal_cli, "secret", "create", name, *[f"{k}={v}" for k, v in pairs.items()], "--force"]
    result = subprocess.run(args, capture_output=True, text=True, check=False)
    if result.returncode != 0:
        # Modal's own error text does not include the secret values.
        sys.exit(f"modal secret create {name} failed:\n{result.stderr.strip() or result.stdout.strip()}")
    print(f"Modal secret '{name}' saved with {len(pairs)} values.")


def cmd_modal(_: argparse.Namespace) -> int:
    """Push artemis-omnigent-deploy and artemis-llm to Modal."""
    values = read_env()
    problems = validate(values)
    if problems:
        print("Fix .env first (python scripts/make_secrets.py check).")
        return 1
    run_modal_secret("artemis-omnigent-deploy", {k: values[k] for k in DEPLOY_KEYS})
    run_modal_secret("artemis-llm", {k: values[k] for k in LLM_KEYS})
    print("Next: modal deploy lab/modal_server.py")
    return 0


def cmd_vercel(_: argparse.Namespace) -> int:
    """Print the Vercel environment variables to add in the dashboard."""
    values = read_env()
    missing = [k for k in VERCEL_KEYS if not is_filled(values.get(k))]
    if missing:
        print("Missing in .env: " + ", ".join(missing))
        return 1
    print("Add these in Vercel > artemis project > Settings > Environment Variables")
    print("(environments: Production, Preview, Development). Mark the secret ones Sensitive.\n")
    for key in VERCEL_KEYS:
        tag = "  [secret]" if key in VERCEL_SECRET_KEYS else ""
        print(f"{key}={values[key]}{tag}")
    print("\nThen redeploy the project so the new values take effect.")
    return 0


def main() -> int:
    """Parse arguments and dispatch to a subcommand."""
    parser = argparse.ArgumentParser(description=__doc__, formatter_class=argparse.RawDescriptionHelpFormatter)
    sub = parser.add_subparsers(dest="command", required=True)
    for name, func in (("init", cmd_init), ("check", cmd_check), ("modal", cmd_modal), ("vercel", cmd_vercel)):
        sub.add_parser(name).set_defaults(func=func)
    args = parser.parse_args()
    return args.func(args)


if __name__ == "__main__":
    raise SystemExit(main())
