"""Deploy the Omnigent server for Artemis on Modal.

This is Artemis's version of Omnigent's own ``deploy/modal/modal_app.py``
(Omnigent 0.16.0). It runs the official, unmodified server image as one
always-on Modal web server and adds two things Artemis needs:

1. **Server-managed sandboxes.** At start-up it writes a small server
   config that turns on ``sandbox.provider: modal``. Every session created
   with ``host_type: "managed"`` then gets its own disposable Modal sandbox
   as its runner, so no laptop has to stay online.
2. **A machine client for the website.** The ``OMNIGENT_MACHINE_*`` values
   in the deploy secret enable Omnigent's OAuth client-credentials grant,
   which is how the Vercel relay authenticates.

Secrets (created by ``scripts/make_secrets.py``, never committed):

``artemis-omnigent-deploy`` (read by this server)
    DATABASE_URL, OMNIGENT_ACCOUNTS_COOKIE_SECRET, OMNIGENT_ACCOUNTS_BASE_URL,
    OMNIGENT_ACCOUNTS_INIT_ADMIN_USERNAME, OMNIGENT_ACCOUNTS_INIT_ADMIN_PASSWORD,
    OMNIGENT_MACHINE_CLIENT_ID,
    OMNIGENT_MACHINE_CLIENT_SECRET_HASH, OMNIGENT_MACHINE_SUB,
    MODAL_TOKEN_ID, MODAL_TOKEN_SECRET

``artemis-llm`` (injected only into the agent sandboxes, never the server)
    OMNIGENT_ANTHROPIC_API_KEY

Deploy from the repository root:

    modal deploy lab/modal_server.py

The public URL is printed by ``modal deploy`` and follows Modal's pattern
``https://<workspace>--artemis-omnigent-server.modal.run``.
"""

from __future__ import annotations

import os
import subprocess
from pathlib import Path

import modal

# The CI-built Omnigent server image, unmodified. Pinning a version tag
# instead of ``latest`` is recommended once Phase 1 passes.
SERVER_IMAGE = "ghcr.io/omnigent-ai/omnigent-server:latest"
# The image's uvicorn port (Omnigent deploy/docker/Dockerfile: EXPOSE 8000).
SERVER_PORT = 8000
# First boot runs database migrations over the network; allow headroom.
STARTUP_TIMEOUT_S = 300
# Where the generated server config is written inside the container.
CONFIG_PATH = Path("/tmp/artemis-omnigent-config.yaml")
# Modal secret whose variables are injected into every agent sandbox.
SANDBOX_LLM_SECRET = "artemis-llm"
# Modal secret read by the server itself.
DEPLOY_SECRET = "artemis-omnigent-deploy"

app = modal.App("artemis-omnigent")

# Durable store for uploaded agent bundles and artifacts.
artifacts = modal.Volume.from_name("artemis-omnigent-artifacts", create_if_missing=True)


def write_server_config(public_url: str, path: Path = CONFIG_PATH) -> Path:
    """Write the Omnigent server config that enables Modal-managed sandboxes.

    :param public_url: This server's public HTTPS URL. Sandboxes dial back
        to it, so it must be reachable from Modal's cloud.
    :param path: Destination file.
    :returns: The path written.
    :raises RuntimeError: If ``public_url`` is not an https URL.
    """
    url = public_url.strip().rstrip("/")
    if not url.startswith("https://"):
        raise RuntimeError(
            "OMNIGENT_ACCOUNTS_BASE_URL must be this server's public https URL, "
            f"got {public_url!r}"
        )
    path.write_text(
        "\n".join(
            [
                "# Generated by lab/modal_server.py at container start.",
                "sandbox:",
                "  provider: modal",
                f"  server_url: {url}",
                "  modal:",
                "    secrets:",
                f"      - {SANDBOX_LLM_SECRET}",
                "",
            ]
        ),
        encoding="utf-8",
    )
    return path


@app.function(
    image=modal.Image.from_registry(SERVER_IMAGE),
    secrets=[modal.Secret.from_name(DEPLOY_SECRET)],
    volumes={"/data/artifacts": artifacts},
    # One always-on container: Omnigent keeps its runner registry in memory,
    # so traffic must land on a single container and must never scale to zero.
    min_containers=1,
    max_containers=1,
    cpu=1.0,
    memory=1024,
    # Each proxied request, SSE stream or WebSocket holds one Modal input for
    # its lifetime; use the platform maximum. Runners reconnect after a cut.
    timeout=24 * 60 * 60,
)
@modal.concurrent(max_inputs=1000)
@modal.web_server(port=SERVER_PORT, startup_timeout=STARTUP_TIMEOUT_S)
def server() -> None:
    """Generate the sandbox config, then launch Omnigent's standard entrypoint."""
    required = [
        "DATABASE_URL",
        "OMNIGENT_ACCOUNTS_COOKIE_SECRET",
        "OMNIGENT_ACCOUNTS_BASE_URL",
        "OMNIGENT_MACHINE_CLIENT_ID",
        "OMNIGENT_MACHINE_CLIENT_SECRET_HASH",
        "OMNIGENT_MACHINE_SUB",
        "MODAL_TOKEN_ID",
        "MODAL_TOKEN_SECRET",
    ]
    missing = [name for name in required if not os.environ.get(name)]
    if missing:
        raise RuntimeError(f"Modal secret {DEPLOY_SECRET!r} is missing: {', '.join(missing)}")

    config_path = write_server_config(os.environ["OMNIGENT_ACCOUNTS_BASE_URL"])
    env = {
        **os.environ,
        "OMNIGENT_CONFIG": str(config_path),
        # Built-in username and password accounts for the Omnigent web UI.
        "OMNIGENT_AUTH_PROVIDER": "accounts",
        "OMNIGENT_AUTH_ENABLED": "1",
    }
    subprocess.Popen(["python", "/app/entrypoint.py"], env=env)
