"""Artemis solar harness: the frozen half of the AutoResearch contract.

DO NOT EDIT THIS FILE. Agents edit experiment.py (or a copy of it in trials/);
humans change this file, and every change shows up in its fingerprint.

The question
------------
Among earth-abundant, non-toxic inorganic crystals in NIST JARVIS-DFT, which
ones should we compute next to find excellent solar absorbers fastest?

A visitor to the lab cannot afford the expensive calculation (the TBmBJ optical
spectrum that yields SLME, the spectroscopic limited maximum efficiency) for
every candidate. The experiment therefore sees only cheap properties (the
OptB88vdW band gap, formation energy, energy above the convex hull, composition
and structure) and must put the candidates in the order it would compute them.
The harness then reveals the hidden SLME labels and counts how many expensive
evaluations that order needed to find the target number of excellent absorbers,
compared with picking candidates at random.

Pre-registered definitions (fixed 2026-10-03 by Claude, owner Peter Alesso)
---------------------------------------------------------------------------
Hit:            SLME >= 30.0 % and energy above hull <= 0.1 eV/atom.
Pool:           materials in the chosen split whose every element has a crustal
                abundance >= 1 mg/kg (CRC Handbook, 97th ed.) and which contain
                none of Cd, Hg, Pb, Tl, As, and no radioactive element.
Primary metric: acceleration = (expected evaluations a random order needs to
                find N hits) / (evaluations this order needed), N = 10 or every
                hit in the pool if there are fewer. Higher is better.
Also reported:  hits in the top 25, enrichment in the top 25, average precision.
Splits:         the official JARVIS-Leaderboard SLME split. "train" is known
                (labels visible); "val" is the search pool used in the loop;
                "test" is used exactly once, at the end, by `final`.

The thresholds were chosen after looking only at aggregate counts of SLME
values per split, so that the target is rare enough to make search matter;
no ranking method was tuned before they were fixed.

Commands
--------
    python lab/solar/harness.py fingerprint
    python lab/solar/harness.py describe
    python lab/solar/harness.py baselines
    python lab/solar/harness.py evaluate --experiment lab/solar/trials/NAME.py --note "..."
    python lab/solar/harness.py shortlist -n 15  # never-assessed materials, no labels
    python lab/solar/harness.py final            # once, at the very end
"""

from __future__ import annotations

import argparse
import ast
import csv
import hashlib
import importlib.util
import io
import json
import multiprocessing as mp
import os
import queue
import subprocess
import sys
import time
import tokenize
import traceback
from dataclasses import dataclass
from datetime import datetime, timezone
from pathlib import Path

import numpy as np
import pandas as pd

HERE = Path(__file__).resolve().parent
REPO_ROOT = HERE.parent.parent
DATA_DIR = HERE / "data"
SNAPSHOT = DATA_DIR / "solar_snapshot.csv.gz"
MANIFEST = DATA_DIR / "snapshot.json"
ABUNDANCE = DATA_DIR / "crustal_abundance_crc97.csv"
DEFAULT_EXPERIMENT = HERE / "experiment.py"
RUNS_DIR = Path(os.environ.get("ARTEMIS_RUNS_DIR", REPO_ROOT / "runs" / "solar"))
LEDGER = RUNS_DIR / "ledger.tsv"
FINAL_RESULT = RUNS_DIR / "final_test.json"

# ---- pre-registered definitions (see module docstring) --------------------
HIT_SLME_PCT = 30.0
HIT_EHULL_MAX_EV = 0.1
TARGET_HITS = 10
TOP_K = 25
MIN_ABUNDANCE_MG_PER_KG = 1.0
EXCLUDED_TOXIC = frozenset({"Cd", "Hg", "Pb", "Tl", "As"})
EXCLUDED_RADIOACTIVE = frozenset({
    "Tc", "Pm", "Po", "At", "Rn", "Fr", "Ra", "Ac", "Th", "Pa", "U", "Np", "Pu",
    "Am", "Cm", "Bk", "Cf", "Es", "Fm", "Md", "No", "Lr",
})
SQ_OPTIMUM_EV = 1.34

# ---- rules of the game ----------------------------------------------------
TIME_BUDGET_S = 300            # wall-clock limit for one call to rank()
EXPERIMENT_BUDGET = 60         # val evaluations allowed per ledger (one lab run)
SEED = 0
VISIBLE_COLUMNS = [
    "jid", "formula", "composition", "elements", "n_elements", "nat",
    "spg_number", "spg_symbol", "crys", "density", "volume_per_atom",
    "optb88vdw_bandgap", "formation_energy_peratom", "ehull",
]
HIDDEN_COLUMNS = ["slme", "mbj_bandgap"]
# An experiment must get its data only from the arguments of rank(). These
# substrings suggest it reads files or reaches around the harness, so the
# harness refuses to run an experiment that contains any of them.
FORBIDDEN_SUBSTRINGS = [
    "solar_snapshot", "snapshot.json", "harness", "ledger", "final_test",
    "open(", "read_csv", "read_table", "read_json", "read_pickle", "np.load",
    "loadtxt", "genfromtxt", "pickle", "joblib.load", "importlib", "__import__",
    "exec(", "eval(", "subprocess", "os.system", "os.popen", "import glob",
    "glob.", "os.walk", "listdir", "scandir", "pathlib", "urllib", "requests",
    "socket", "http", "builtins", "globals()", "getattr(",
]
LEDGER_FIELDS = [
    "utc", "kind", "split", "experiment", "experiment_sha12", "git_commit",
    "status", "pool_size", "pool_hits", "target_hits", "evals_to_target",
    "random_expected", "acceleration", "hits_at_k", "enrichment_at_k",
    "average_precision", "seconds", "harness_sha12", "snapshot_sha12", "note",
]


class HarnessError(RuntimeError):
    """A problem the harness explains in plain language instead of a traceback."""


@dataclass(frozen=True)
class Task:
    """Everything one evaluation needs.

    train:       every material in the train split, all columns (labels known).
    candidates:  the pool for the chosen split, visible columns only, shuffled.
    hidden:      the pool's hidden labels, indexed by jid (never shown).
    """

    split: str
    train: pd.DataFrame
    candidates: pd.DataFrame
    hidden: pd.DataFrame


# ---------------------------------------------------------------- integrity
def sha256_file(path: Path) -> str:
    """Return the hex SHA-256 of the file at *path*."""
    digest = hashlib.sha256()
    with open(path, "rb") as handle:
        for block in iter(lambda: handle.read(1 << 20), b""):
            digest.update(block)
    return digest.hexdigest()


def fingerprint() -> dict[str, str]:
    """Return the SHA-256 of the harness, the snapshot and the abundance table."""
    out = {"harness": sha256_file(Path(__file__).resolve())}
    out["snapshot"] = sha256_file(SNAPSHOT) if SNAPSHOT.exists() else "missing"
    out["abundance"] = sha256_file(ABUNDANCE)
    return out


def load_snapshot() -> pd.DataFrame:
    """Load the frozen snapshot after checking it against its manifest."""
    if not SNAPSHOT.exists() or not MANIFEST.exists():
        raise HarnessError(
            "The data snapshot is missing. A human builds it once with "
            "`modal run lab/solar/prepare_data.py` and commits "
            "lab/solar/data/solar_snapshot.csv.gz and snapshot.json."
        )
    manifest = json.loads(MANIFEST.read_text(encoding="utf-8"))
    actual = sha256_file(SNAPSHOT)
    if actual != manifest.get("sha256"):
        raise HarnessError(
            f"The snapshot does not match its manifest (expected "
            f"{str(manifest.get('sha256'))[:12]}, found {actual[:12]}). "
            "Someone changed the data; restore it from git before continuing."
        )
    frame = pd.read_csv(SNAPSHOT, dtype={"jid": str, "split": str, "formula": str,
                                         "composition": str, "elements": str,
                                         "spg_symbol": str, "crys": str})
    for column in ("formula", "composition", "elements", "spg_symbol", "crys"):
        frame[column] = frame[column].fillna("")
    return frame


def load_abundance() -> dict[str, float]:
    """Return {element symbol: crustal abundance in mg/kg} from the cited table."""
    table: dict[str, float] = {}
    with open(ABUNDANCE, encoding="utf-8") as handle:
        rows = (line for line in handle if not line.startswith("#"))
        for row in csv.DictReader(rows):
            table[row["symbol"].strip()] = float(row["mg_per_kg"])
    return table


# ---------------------------------------------------------------- the task
def element_list(value: str) -> list[str]:
    """Split the snapshot's space-separated element list."""
    return [e for e in str(value or "").split() if e]


def pool_mask(frame: pd.DataFrame, abundance: dict[str, float]) -> pd.Series:
    """True for rows that are earth-abundant, non-toxic and non-radioactive."""
    def allowed(elements: str) -> bool:
        items = element_list(elements)
        if not items:
            return False
        for element in items:
            if element in EXCLUDED_TOXIC or element in EXCLUDED_RADIOACTIVE:
                return False
            if abundance.get(element, 0.0) < MIN_ABUNDANCE_MG_PER_KG:
                return False
        return True

    return frame["elements"].map(allowed)


def hit_mask(hidden: pd.DataFrame, ehull: pd.Series) -> pd.Series:
    """True for excellent, stable absorbers under the pre-registered definition."""
    slme = pd.to_numeric(hidden["slme"], errors="coerce")
    stable = pd.to_numeric(ehull, errors="coerce") <= HIT_EHULL_MAX_EV
    return (slme >= HIT_SLME_PCT) & stable.fillna(False)


def build_task(split: str) -> Task:
    """Assemble the train set, the shuffled candidate pool and its hidden labels."""
    if split not in ("val", "test"):
        raise HarnessError("split must be 'val' (the search loop) or 'test' (final only)")
    frame = load_snapshot()
    abundance = load_abundance()
    train = frame[frame["split"] == "train"].drop(columns=["split"]).reset_index(drop=True)
    pool = frame[(frame["split"] == split) & pool_mask(frame, abundance)]
    pool = pool.sample(frac=1.0, random_state=SEED).reset_index(drop=True)
    candidates = pool[VISIBLE_COLUMNS].copy()
    hidden = pool[["jid", *HIDDEN_COLUMNS]].copy()
    hidden["hit"] = hit_mask(hidden, pool["ehull"]).to_numpy()
    hidden = hidden.set_index("jid")
    return Task(split=split, train=train, candidates=candidates, hidden=hidden)


# ---------------------------------------------------------------- scoring
def validate_ranking(ranking: object, pool_ids: list[str]) -> list[str]:
    """Check the ranking is a permutation of the pool's jids; return it as a list."""
    if isinstance(ranking, (pd.Series, pd.Index, np.ndarray)):
        ranking = list(ranking)
    if not isinstance(ranking, (list, tuple)):
        raise HarnessError(f"rank() must return a list of jids, got {type(ranking).__name__}")
    ranking = [str(j) for j in ranking]
    expected = set(pool_ids)
    if len(ranking) != len(expected) or set(ranking) != expected:
        missing = len(expected - set(ranking))
        extra = len(set(ranking) - expected)
        dupes = len(ranking) - len(set(ranking))
        raise HarnessError(
            f"rank() must return every candidate jid exactly once "
            f"({missing} missing, {extra} unknown, {dupes} repeated)."
        )
    return ranking


def score_ranking(ranking: list[str], hidden: pd.DataFrame) -> dict[str, float | int]:
    """Score an ordering of the pool against the hidden hit labels."""
    hits = hidden["hit"].reindex(ranking).to_numpy(dtype=bool)
    pool_size = len(ranking)
    pool_hits = int(hits.sum())
    if pool_hits == 0:
        raise HarnessError("The pool contains no hits, so no ordering can be scored.")
    target = min(TARGET_HITS, pool_hits)
    positions = np.flatnonzero(hits) + 1                 # 1-based ranks of hits
    evals_to_target = int(positions[target - 1])
    random_expected = target * (pool_size + 1) / (pool_hits + 1)
    k = min(TOP_K, pool_size)
    hits_at_k = int(hits[:k].sum())
    base_rate = pool_hits / pool_size
    precision_at_hits = np.arange(1, pool_hits + 1) / positions
    return {
        "pool_size": pool_size,
        "pool_hits": pool_hits,
        "target_hits": target,
        "evals_to_target": evals_to_target,
        "random_expected": round(random_expected, 2),
        "acceleration": round(random_expected / evals_to_target, 3),
        "hits_at_k": hits_at_k,
        "enrichment_at_k": round((hits_at_k / k) / base_rate, 3),
        "average_precision": round(float(precision_at_hits.mean()), 4),
    }


# ---------------------------------------------------------------- baselines
def rank_sq_gap(candidates: pd.DataFrame) -> list[str]:
    """Order by distance of the OptB88vdW gap from the Shockley-Queisser optimum."""
    distance = (pd.to_numeric(candidates["optb88vdw_bandgap"], errors="coerce")
                - SQ_OPTIMUM_EV).abs().fillna(np.inf)
    ordered = candidates.assign(_d=distance).sort_values(["_d", "jid"], kind="mergesort")
    return ordered["jid"].tolist()


def rank_sq_gap_stable(candidates: pd.DataFrame) -> list[str]:
    """Stable candidates (ehull <= 0.1) first, each group ordered by gap distance."""
    distance = (pd.to_numeric(candidates["optb88vdw_bandgap"], errors="coerce")
                - SQ_OPTIMUM_EV).abs().fillna(np.inf)
    unstable = ~(pd.to_numeric(candidates["ehull"], errors="coerce") <= HIT_EHULL_MAX_EV)
    ordered = candidates.assign(_u=unstable.astype(int), _d=distance).sort_values(
        ["_u", "_d", "jid"], kind="mergesort")
    return ordered["jid"].tolist()


def random_baseline(hidden: pd.DataFrame, draws: int = 2000) -> dict[str, float]:
    """Average score of random orderings (checks the analytic expectation)."""
    rng = np.random.default_rng(SEED)
    ids = hidden.index.to_numpy()
    accel, evals = [], []
    for _ in range(draws):
        result = score_ranking(list(rng.permutation(ids)), hidden)
        accel.append(result["acceleration"])
        evals.append(result["evals_to_target"])
    return {"mean_evals_to_target": round(float(np.mean(evals)), 2),
            "mean_acceleration": round(float(np.mean(accel)), 3)}


# ---------------------------------------------------------------- experiments
def strip_comments_and_docstrings(source: str) -> str:
    """Blank out comments and docstrings so prose cannot trip the static check."""
    lines = source.splitlines(keepends=True)
    spans: list[tuple[tuple[int, int], tuple[int, int]]] = []
    try:
        tree = ast.parse(source)
    except SyntaxError:
        return source
    for node in ast.walk(tree):
        if isinstance(node, (ast.Module, ast.FunctionDef, ast.AsyncFunctionDef, ast.ClassDef)):
            body = getattr(node, "body", [])
            if (body and isinstance(body[0], ast.Expr) and isinstance(body[0].value, ast.Constant)
                    and isinstance(body[0].value.value, str)):
                doc = body[0]
                spans.append(((doc.lineno, doc.col_offset), (doc.end_lineno, doc.end_col_offset)))
    try:
        for token in tokenize.generate_tokens(io.StringIO(source).readline):
            if token.type == tokenize.COMMENT:
                spans.append((token.start, token.end))
    except (tokenize.TokenError, IndentationError):
        return source
    chars = [list(line) for line in lines]
    for (row0, col0), (row1, col1) in spans:
        for row in range(row0, row1 + 1):
            line = chars[row - 1]
            start = col0 if row == row0 else 0
            stop = col1 if row == row1 else len(line)
            for i in range(start, min(stop, len(line))):
                if line[i] != "\n":
                    line[i] = " "
    return "".join("".join(line) for line in chars)


def static_check(source: str) -> list[str]:
    """Return forbidden substrings found in an experiment's code (not its prose)."""
    code = strip_comments_and_docstrings(source)
    return [s for s in FORBIDDEN_SUBSTRINGS if s in code]


def _child(path: str, train: pd.DataFrame, candidates: pd.DataFrame, out: mp.Queue) -> None:
    """Run rank() in a separate process so a runaway experiment can be stopped."""
    try:
        np.random.seed(SEED)
        spec = importlib.util.spec_from_file_location("artemis_experiment", path)
        module = importlib.util.module_from_spec(spec)
        assert spec.loader is not None
        spec.loader.exec_module(module)
        if not hasattr(module, "rank"):
            raise HarnessError("the experiment must define rank(train, candidates, seed)")
        ranking = module.rank(train.copy(), candidates.copy(), seed=SEED)
        if isinstance(ranking, (pd.Series, pd.Index, np.ndarray)):
            ranking = list(ranking)
        out.put(("ok", [str(j) for j in ranking]))
    except BaseException:  # noqa: BLE001 - report every failure to the parent
        out.put(("error", traceback.format_exc(limit=6)))


def run_rank(path: Path, task: Task) -> tuple[list[str], float]:
    """Import the experiment at *path*, call rank() under the time budget."""
    source = path.read_text(encoding="utf-8")
    found = static_check(source)
    if found:
        raise HarnessError(
            "The experiment contains forbidden code (" + ", ".join(found) + "). "
            "Experiments must use only the train and candidates arguments."
        )
    context = mp.get_context("spawn")
    channel = context.Queue()
    worker = context.Process(target=_child, args=(str(path), task.train, task.candidates, channel))
    started = time.time()
    worker.start()
    try:
        status, payload = channel.get(timeout=TIME_BUDGET_S)
    except queue.Empty:
        worker.terminate()
        worker.join(5)
        raise HarnessError(f"rank() took longer than the {TIME_BUDGET_S} s budget.")
    finally:
        worker.join(5)
        if worker.is_alive():
            worker.terminate()
    seconds = time.time() - started
    if status != "ok":
        raise HarnessError("rank() raised an error:\n" + str(payload))
    return payload, seconds


# ---------------------------------------------------------------- ledger
def git_commit() -> str:
    """Return the short git commit of the repository, or '' if unavailable."""
    try:
        out = subprocess.run(["git", "-C", str(REPO_ROOT), "rev-parse", "--short", "HEAD"],
                             capture_output=True, text=True, timeout=10)
        return out.stdout.strip()
    except (OSError, subprocess.SubprocessError):
        return ""


def read_ledger() -> list[dict[str, str]]:
    """Return the ledger rows (empty if there is no ledger yet)."""
    if not LEDGER.exists():
        return []
    with open(LEDGER, encoding="utf-8", newline="") as handle:
        return list(csv.DictReader(handle, delimiter="\t"))


def append_ledger(row: dict[str, object]) -> None:
    """Append one row to the ledger, writing the header the first time."""
    RUNS_DIR.mkdir(parents=True, exist_ok=True)
    new = not LEDGER.exists()
    with open(LEDGER, "a", encoding="utf-8", newline="") as handle:
        writer = csv.DictWriter(handle, fieldnames=LEDGER_FIELDS, delimiter="\t",
                                extrasaction="ignore")
        if new:
            writer.writeheader()
        clean = {k: str(row.get(k, "")).replace("\t", " ").replace("\n", " ") for k in LEDGER_FIELDS}
        writer.writerow(clean)


def base_row(kind: str, split: str, experiment: str, experiment_sha: str) -> dict[str, object]:
    """Fields shared by every ledger row."""
    prints = fingerprint()
    return {
        "utc": datetime.now(timezone.utc).strftime("%Y-%m-%dT%H:%M:%SZ"),
        "kind": kind, "split": split, "experiment": experiment,
        "experiment_sha12": experiment_sha[:12], "git_commit": git_commit(),
        "harness_sha12": prints["harness"][:12], "snapshot_sha12": prints["snapshot"][:12],
    }


def relative(path: Path) -> str:
    """Show *path* relative to the repository root when possible."""
    try:
        return str(path.resolve().relative_to(REPO_ROOT))
    except ValueError:
        return str(path)


# ---------------------------------------------------------------- commands
def cmd_fingerprint(_: argparse.Namespace) -> int:
    print(json.dumps(fingerprint(), indent=2))
    return 0


def cmd_describe(_: argparse.Namespace) -> int:
    task = build_task("val")
    frame = load_snapshot()
    abundance = load_abundance()
    test_pool = int(((frame["split"] == "test") & pool_mask(frame, abundance)).sum())
    info = {
        "question": "Order earth-abundant candidates so the expensive SLME calculation "
                    "finds excellent, stable absorbers with as few evaluations as possible.",
        "hit": f"SLME >= {HIT_SLME_PCT}% and ehull <= {HIT_EHULL_MAX_EV} eV/atom",
        "train_rows": len(task.train),
        "train_hits": int(hit_mask(task.train, task.train["ehull"]).sum()),
        "val_pool_size": len(task.candidates),
        "val_pool_hits": int(task.hidden["hit"].sum()),
        "test_pool_size": test_pool,
        "unlabeled_pool_size": int(((frame["split"] == "unlabeled") & pool_mask(frame, abundance)).sum()),
        "target_hits": min(TARGET_HITS, int(task.hidden["hit"].sum())),
        "visible_columns": VISIBLE_COLUMNS,
        "hidden_columns": HIDDEN_COLUMNS,
        "train_columns": list(task.train.columns),
        "time_budget_s": TIME_BUDGET_S,
        "experiment_budget": EXPERIMENT_BUDGET,
        "experiments_used": sum(1 for r in read_ledger()
                                if r["kind"] == "experiment" and r["split"] == "val"),
    }
    print(json.dumps(info, indent=2))
    return 0


def cmd_baselines(args: argparse.Namespace) -> int:
    split = args.split
    if split == "test":
        raise HarnessError("Baselines on test are computed only by `final`.")
    task = build_task(split)
    rows = baseline_scores(task)
    for name, result in rows.items():
        row = base_row("baseline", split, name, "")
        row.update({k: v for k, v in result.items() if k in LEDGER_FIELDS})
        row.update(status="ok", note=f"reference baseline {name}")
        append_ledger(row)
    print(json.dumps(rows, indent=2))
    return 0


def baseline_scores(task: Task) -> dict[str, dict[str, object]]:
    """Score the reference orderings on *task*."""
    rows: dict[str, dict[str, object]] = {}
    expected = score_ranking(list(task.hidden.index), task.hidden)  # for pool stats only
    random_avg = random_baseline(task.hidden)
    # By definition random search has acceleration 1.0; the simulated mean
    # number of evaluations is reported as a check on the analytic formula.
    rows["random"] = {
        "pool_size": expected["pool_size"], "pool_hits": expected["pool_hits"],
        "target_hits": expected["target_hits"],
        "evals_to_target": expected["random_expected"],
        "random_expected": expected["random_expected"],
        "acceleration": 1.0,
        "simulated_mean_evals_to_target": random_avg["mean_evals_to_target"],
    }
    rows["sq_gap"] = score_ranking(rank_sq_gap(task.candidates), task.hidden)
    rows["sq_gap_stable"] = score_ranking(rank_sq_gap_stable(task.candidates), task.hidden)
    return rows


def evaluate(path: Path, split: str, kind: str, note: str) -> dict[str, object]:
    """Run one experiment on *split*, append it to the ledger and return the row."""
    if not path.exists():
        raise HarnessError(f"No experiment file at {path}")
    experiment_sha = sha256_file(path)
    row = base_row(kind, split, relative(path), experiment_sha)
    row["note"] = note
    task = build_task(split)
    try:
        ranking, seconds = run_rank(path, task)
        ranking = validate_ranking(ranking, list(task.candidates["jid"]))
        row.update(score_ranking(ranking, task.hidden))
        row.update(status="ok", seconds=round(seconds, 2))
    except HarnessError as exc:
        row.update(status="invalid", note=f"{note} | {exc}"[:500])
        append_ledger(row)
        raise
    append_ledger(row)
    return row


def cmd_evaluate(args: argparse.Namespace) -> int:
    used = sum(1 for r in read_ledger() if r["kind"] == "experiment" and r["split"] == "val")
    if used >= EXPERIMENT_BUDGET:
        raise HarnessError(
            f"The experiment budget of {EXPERIMENT_BUDGET} val evaluations is used up. "
            "Write up the results and run `final`."
        )
    path = Path(args.experiment).resolve()
    best = best_val_row()
    row = evaluate(path, "val", "experiment", args.note or "")
    row["best_previous_acceleration"] = best
    row["experiments_used"] = used + 1
    print("RESULT " + json.dumps(row))
    return 0


def best_val_row() -> float | None:
    """Best val acceleration in the ledger among valid experiments and baselines."""
    values = []
    for r in read_ledger():
        if r["split"] == "val" and r["status"] == "ok" and r["acceleration"]:
            values.append(float(r["acceleration"]))
    return max(values) if values else None


def cmd_final(args: argparse.Namespace) -> int:
    if FINAL_RESULT.exists() and not args.i_am_a_human_rerunning:
        raise HarnessError(
            f"The test split was already used ({relative(FINAL_RESULT)}). "
            "The final score is reported once; it is never re-run to get a better number."
        )
    path = Path(args.experiment).resolve()
    row = evaluate(path, "test", "final", args.note or "final held-out test")
    task = build_task("test")
    result = {"experiment": row, "baselines": baseline_scores(task),
              "fingerprint": fingerprint(),
              "definitions": {"hit_slme_pct": HIT_SLME_PCT, "hit_ehull_max_ev": HIT_EHULL_MAX_EV,
                              "target_hits": TARGET_HITS, "top_k": TOP_K,
                              "min_abundance_mg_per_kg": MIN_ABUNDANCE_MG_PER_KG,
                              "excluded_toxic": sorted(EXCLUDED_TOXIC)}}
    RUNS_DIR.mkdir(parents=True, exist_ok=True)
    FINAL_RESULT.write_text(json.dumps(result, indent=2) + "\n", encoding="utf-8")
    print("FINAL " + json.dumps(result))
    return 0


def unlabeled_task() -> tuple[pd.DataFrame, pd.DataFrame]:
    """Train on train+val labels; candidates are never-assessed earth-abundant materials."""
    frame = load_snapshot()
    abundance = load_abundance()
    train = frame[frame["split"].isin(["train", "val"])].drop(columns=["split"])
    pool = frame[(frame["split"] == "unlabeled") & pool_mask(frame, abundance)]
    pool = pool.sample(frac=1.0, random_state=SEED).reset_index(drop=True)
    return train.reset_index(drop=True), pool[VISIBLE_COLUMNS].copy()


def cmd_shortlist(args: argparse.Namespace) -> int:
    """Print an experiment's top candidates with visible columns only (no labels).

    --pool unlabeled (default): materials JARVIS never assessed for SLME. These
    are the lab's real recommendations for what to compute next.
    --pool val: the search pool, to inspect what an ordering favours.
    """
    path = Path(args.experiment).resolve()
    if args.pool == "val":
        task = build_task("val")
    else:
        train, candidates = unlabeled_task()
        task = Task(split="unlabeled", train=train, candidates=candidates,
                    hidden=pd.DataFrame(index=candidates["jid"]))
    ranking, _ = run_rank(path, task)
    ranking = validate_ranking(ranking, list(task.candidates["jid"]))
    top = task.candidates.set_index("jid").loc[ranking[: args.n]].reset_index()
    top.insert(0, "rank", range(1, len(top) + 1))
    print(f"# pool={args.pool} size={len(task.candidates)} experiment={relative(path)} "
          f"experiment_sha12={sha256_file(path)[:12]}")
    print(top.to_csv(index=False))
    return 0


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(description="Artemis solar harness (frozen).")
    sub = parser.add_subparsers(dest="command", required=True)
    sub.add_parser("fingerprint", help="SHA-256 of harness, snapshot and abundance table")
    sub.add_parser("describe", help="the task, pool sizes and budgets")
    p = sub.add_parser("baselines", help="score random and Shockley-Queisser baselines")
    p.add_argument("--split", default="val", choices=["val"])
    p = sub.add_parser("evaluate", help="score one experiment on the val pool")
    p.add_argument("--experiment", default=str(DEFAULT_EXPERIMENT))
    p.add_argument("--note", default="")
    p = sub.add_parser("shortlist", help="top candidates of an experiment (no labels)")
    p.add_argument("--experiment", default=str(DEFAULT_EXPERIMENT))
    p.add_argument("--pool", default="unlabeled", choices=["unlabeled", "val"])
    p.add_argument("-n", type=int, default=15)
    p = sub.add_parser("final", help="score the promoted experiment on test, once")
    p.add_argument("--experiment", default=str(DEFAULT_EXPERIMENT))
    p.add_argument("--note", default="")
    p.add_argument("--i-am-a-human-rerunning", action="store_true", help=argparse.SUPPRESS)
    args = parser.parse_args(argv)
    handlers = {"fingerprint": cmd_fingerprint, "describe": cmd_describe,
                "baselines": cmd_baselines, "evaluate": cmd_evaluate,
                "shortlist": cmd_shortlist, "final": cmd_final}
    try:
        return handlers[args.command](args)
    except HarnessError as exc:
        print(f"HARNESS: {exc}")
        return 1


if __name__ == "__main__":
    sys.exit(main())
