"""Artemis Langlands harness: the frozen half of the AutoResearch contract.

DO NOT EDIT THIS FILE. Agents edit experiment.py (or a copy of it in trials/);
humans change this file, and every change shows up in its fingerprint.

The program tests two research suggestions (R1) from P. Alesso, "Euler's
identity and the Langlands program" (research memo, 2026).

Part A, murmurations and the archimedean sign (fixed measurements)
------------------------------------------------------------------
Over Q the global root number of an elliptic curve is w = -(product of its
local root numbers at the bad primes); the leading minus sign is the
archimedean factor, Euler's e^{i pi} = -1. Over a real quadratic field such as
Q(sqrt 5) there are two real places and w = +(product of the finite local
signs). Murmurations (He, Lee, Oliver and Pozdnyakov 2022; Zubrilina 2023)
correlate a_p with w. The memo predicts that over Q(sqrt 5) the murmuration
pattern follows +(product of finite signs), the opposite of the convention
over Q for the same finite data.

  C1  Reproduction over Q. For each class with conductor N in [1000, 5000)
      and each good prime p <= N, x = p/N falls in one of ten bins of width
      0.1 on [0, 1] (the last bin includes x = 1). M_Q(b) is the mean of w * a_p / sqrt(p) in bin b; P+ and
      P- are the means of a_p / sqrt(p) over classes with w = +1 and w = -1.
      Reproduced if corr(P+, P-) < 0 with its 95 percent bootstrap interval
      below 0 (the mirror image in the published plots) and M_Q changes sign
      at least once across the ten bins.
  C2  The predicted flip over Q(sqrt 5). Same construction over classes with
      conductor norm in [1000, 5000), using the degree-one primes P not
      dividing the conductor, with p = norm(P) <= the conductor norm, x = p
      divided by the conductor norm. Primary statistic: rho_ss, the Pearson
      correlation over the ten bins between M_Q and F_ss, where F_ss(b) is
      the mean of S * a_P / sqrt(p) over SEMISTABLE classes and S is the
      product of the finite local signs computed from the bad primes alone
      (S = product of -a_P at the multiplicative primes; no root-number
      routine involved). The prediction is rho_ss > 0; "no archimedean
      effect", i.e. the Q convention carried over, predicts rho_ss < 0.
      Verdict: "consistent with the predicted flip" if the 95 percent
      interval of rho_ss lies above 0, "contradicts the prediction" if it
      lies below 0, otherwise "inconclusive". Also reported: rho_all over all
      classes with PARI's global root number, the first-bin values, and a
      sensitivity check without the classes that have a model with rational
      coefficients (base changes from Q, which inherit Q's a_p).
  Bootstrap: 2,000 draws resampling whole conductors (Q) and whole conductor
  norms (Q(sqrt 5), which keeps Galois-conjugate classes together), seed 0.
  Pilot ranges (N < 1000, norm < 1000) may be computed freely with
  `murmurations`; the confirmatory ranges are computed once, by `final`.

Part B, does the local sign vector depend on rank? (the AutoResearch loop)
-------------------------------------------------------------------------
Rank 0 and rank 2 curves over Q both have w = +1, so the product of their
local signs is the same (-1). The memo asks whether the distribution of the
vector (w_p) for p | N depends on rank at all. The confound is the conductor:
rank-2 curves have different conductors. So the harness compares classes
that share the SAME conductor N, where the primes and exponents are
identical and only the signs differ.

  Data: every isogeny class over Q with N < 500,000 and rank 0 or 2 (Cremona's
  tables; 1,069,314 classes). Splits by conductor: train N < 300,000; val
  300,000 <= N < 400,000; test 400,000 <= N < 500,000 (used once, by final).
  The experiment defines score(train, rows, seed). train is a list of
  {"N", "bad": [[p, e, w_p], ...], "rank"}; rows are the classes to score,
  {"N", "bad"} only, one per distinct (N, sign pattern), and every class
  with that pattern receives its score. A higher score means "more likely
  rank 2". Experiments never see a_p, the curve, or its label, and never the
  data file's own order (Cremona's class letters), which is correlated with
  rank; see score_split().
  Metric: within-conductor AUC. Over every pair (rank-2 class, rank-0 class)
  with the same N, the fraction in which the rank-2 class scores higher
  (ties count one half). Because a row is fully determined by N and its
  signs, a score can only beat 0.5 here through the signs. Under the null
  hypothesis that, within a conductor, the sign vectors are exchangeable
  between rank-0 and rank-2 classes, the AUC is 0.5; the harness reports the
  stratified Wilcoxon z (exact permutation mean and variance with ties) and
  a 95 percent bootstrap interval over conductors.
  Keep rule (program.md): a trial is a candidate if its val AUC beats the
  current best by at least 0.002 and the paired bootstrap 95 percent
  interval of the difference lies above 0.
  Final (once): experiment.py is trained on train + val with seed 0 and
  scores test. Pre-registered hypotheses, each one-sided at p < 0.01:
    H_B1  the frozen simple rule (number of split multiplicative primes,
          i.e. w_p = -1 with p || N) has within-conductor AUC > 0.5 on test;
    H_B2  the lab's promoted experiment has within-conductor AUC > 0.5 on test.
  Reported with the normal-approximation p, a 2,000-draw within-conductor
  permutation p (seed 0), and the bootstrap interval. The positive control
  (a Nagao-type sum over a_p at good primes below 100, which experiments
  never see) shows the size of the rank signal the metric can detect.

Commands
--------
    python lab/langlands/harness.py fingerprint
    python lab/langlands/harness.py describe
    python lab/langlands/harness.py baselines
    python lab/langlands/harness.py murmurations          # pilot ranges only
    python lab/langlands/harness.py probe --experiment lab/langlands/trials/NAME.py
    python lab/langlands/harness.py evaluate --experiment lab/langlands/trials/NAME.py --note "..."
    python lab/langlands/harness.py recheck --experiment lab/langlands/trials/NAME.py
    python lab/langlands/harness.py final                 # once, at the very end

Every evaluation writes a "started" row to the ledger before it runs and a
result row after; budgets count the started rows, so an interrupted
evaluation still counts.
"""

from __future__ import annotations

import argparse
import ast
import contextlib
import csv
import gzip
import hashlib
import json
import math
import os
import queue
import secrets
import signal
import subprocess
import sys
import tempfile
import threading
import time
import uuid
from datetime import datetime, timezone
from pathlib import Path

import numpy as np

try:  # Linux and macOS (the lab's sandbox). Windows lacks both modules.
    import fcntl
    import resource
except ImportError:  # pragma: no cover - only on Windows
    fcntl = None
    resource = None

HERE = Path(__file__).resolve().parent
REPO_ROOT = HERE.parent.parent
DATA_DIR = HERE / "data"
MANIFEST = DATA_DIR / "manifest.json"
RANK_SIGNS = DATA_DIR / "rank_signs.tsv.gz"
MURM_Q = DATA_DIR / "murm_q.jsonl.gz"
MURM_K = DATA_DIR / "murm_k.jsonl.gz"
RAW_K = DATA_DIR / "raw" / "lmfdb_ec_nf_2.2.5.1_20261008.txt"
RUNNER = HERE / "runner.py"
DEFAULT_EXPERIMENT = HERE / "experiment.py"
# Humans may point local checks elsewhere; the lab never sets this.
RUNS_DIR = Path(os.environ.get("ARTEMIS_RUNS_DIR", REPO_ROOT / "runs" / "langlands"))
LEDGER = RUNS_DIR / "ledger.tsv"
DETAILS_DIR = RUNS_DIR / "details"
FINAL_RESULT = RUNS_DIR / "final_test.json"
FINAL_STARTED = RUNS_DIR / "final_started"
LOCK = RUNS_DIR / "eval.lock"

# ---- pre-registered definitions (see module docstring) --------------------
TRAIN_MAX_N = 300_000
VAL_MAX_N = 400_000
TEST_MAX_N = 500_000
PROBE_FIT_MAX_N = 200_000        # probe: fit below this, score up to TRAIN_MAX_N
SEED = 0
RECHECK_SEEDS = (1, 2)
BOOTSTRAP_DRAWS = 2_000
PERMUTATIONS = 2_000
ALPHA = 0.01
KEEP_MIN_GAIN = 0.002
BINS = 10
Q_PILOT = (11, 1_000)
Q_CONFIRM = (1_000, 5_000)
K_PILOT = (1, 1_000)
K_CONFIRM = (1_000, 5_000)
PRIMES_BELOW_100 = (2, 3, 5, 7, 11, 13, 17, 19, 23, 29, 31, 37, 41, 43, 47, 53, 59, 61,
                    67, 71, 73, 79, 83, 89, 97)

# ---- rules of the game ----------------------------------------------------
EXPERIMENT_BUDGET = 40           # val evaluations per ledger (one lab run)
RECHECK_BUDGET = 16              # seed runs for the Skeptic (8 rechecks of seeds 1 and 2)
READY_TIMEOUT_S = 300.0          # reading the data and imports, before score() starts
TIME_LIMIT_S = 600.0             # score() must answer within this many seconds
CPU_FACTOR = 1.10                # CPU may not exceed 1.10 x wall time + 30 s (one core)
CPU_GRACE_S = 30.0

# ---- what an experiment may contain ------------------------------------------
MAX_EXPERIMENT_BYTES = 40_000
MAX_NUMERIC_CONSTANTS = 300
MAX_LITERAL_ELEMENTS = 50
MAX_STRING_CHARS = 2_000         # outside docstrings
MAX_STRING_CONSTANT = 200        # characters in any one string constant
MAX_INT_MAGNITUDE = 2 ** 63      # one huge integer could carry a whole table
ALLOWED_IMPORTS = frozenset({
    "numpy", "scipy", "sklearn", "math", "heapq", "itertools", "collections", "random",
    "time", "functools", "bisect", "statistics", "array", "copy", "enum", "abc",
    "__future__",
})
# Submodules that may be imported by name (an allowlist; nothing deeper).
ALLOWED_SUBMODULES = {
    "numpy": frozenset({"linalg", "random", "fft", "polynomial"}),
    "scipy": frozenset({"stats", "special", "optimize", "sparse", "linalg", "spatial", "cluster",
                        "interpolate", "integrate", "signal", "ndimage", "fft"}),
    "sklearn": frozenset({"linear_model", "ensemble", "tree", "preprocessing", "metrics",
                          "model_selection", "neighbors", "svm", "naive_bayes", "decomposition",
                          "neural_network", "isotonic", "calibration", "pipeline",
                          "discriminant_analysis", "kernel_approximation", "cluster", "base",
                          "inspection", "kernel_ridge", "gaussian_process", "mixture",
                          "multiclass", "dummy", "compose", "impute", "covariance",
                          "feature_selection"}),
    "collections": frozenset({"abc"}),
}
BANNED_NAMES = frozenset({
    "open", "exec", "eval", "compile", "__import__", "globals", "locals", "vars",
    "getattr", "setattr", "delattr", "breakpoint", "input", "memoryview", "help",
    "exit", "quit", "sys", "os", "io", "types", "inspect", "importlib", "builtins",
})
BANNED_ATTRIBUTES = frozenset({
    "fromfile", "tofile", "save", "savez", "savez_compressed", "load", "loadtxt",
    "savetxt", "genfromtxt", "memmap", "DataSource", "fromregex", "ctypeslib", "lib",
    "core", "testing", "f2py", "distutils", "read", "write", "os", "sys", "subprocess",
    "system", "popen", "io", "datasets", "externals", "joblib", "utils", "misc", "dump",
    "dumps", "loads", "Parallel", "parallel_backend", "ma", "mrecords", "rec",
    "fromtextfile", "load_npz", "save_npz", "npyio", "feature_extraction", "importlib",
    "builtins", "modules", "inspect", "types", "environ", "getenv", "attrgetter",
    "methodcaller", "singledispatch", "singledispatchmethod", "get_type_hints",
    "ForwardRef", "tb_frame", "tb_next", "f_globals", "f_locals", "f_builtins", "f_back",
    "f_code", "gi_frame", "gi_code", "cr_frame", "cr_code", "ag_frame", "co_code",
    "co_consts", "with_traceback",
})
LEDGER_FIELDS = [
    "utc", "kind", "split", "experiment", "experiment_sha12", "git_commit", "status",
    "seeds", "auc_within", "ci95_low", "ci95_high", "z", "p_one_sided", "pairs",
    "conductors", "delta_vs_best", "delta_ci95_low", "delta_ci95_high", "seconds",
    "cpu_seconds", "harness_sha12", "data_sha12", "note",
]
if "ARTEMIS_RUNS_DIR" in os.environ:  # visible in every transcript
    print(f"NOTE: ARTEMIS_RUNS_DIR is set; records go to {RUNS_DIR}, not the lab's ledger.", flush=True)


class HarnessError(RuntimeError):
    """A problem the harness explains in plain language instead of a traceback."""


# ---------------------------------------------------------------- integrity
def sha256_file(path: Path) -> str:
    """Return the hex SHA-256 of the file at *path*."""
    digest = hashlib.sha256()
    with open(path, "rb") as handle:
        for block in iter(lambda: handle.read(1 << 20), b""):
            digest.update(block)
    return digest.hexdigest()


def data_digest() -> str:
    """One SHA-256 over the three frozen data files (in a fixed order)."""
    digest = hashlib.sha256()
    for path in (RANK_SIGNS, MURM_Q, MURM_K, RAW_K):
        digest.update(sha256_file(path).encode("ascii") if path.exists() else b"missing")
    return digest.hexdigest()


def fingerprint() -> dict[str, str]:
    """Return the SHA-256 of the harness, the runner and the data snapshot."""
    return {
        "harness": sha256_file(Path(__file__).resolve()),
        "runner": sha256_file(RUNNER),
        "data": data_digest(),
    }


def check_data() -> dict:
    """Check the frozen snapshot against its manifest and return the manifest."""
    if not MANIFEST.exists() or not all(p.exists() for p in (RANK_SIGNS, MURM_Q, MURM_K)):
        raise HarnessError("The data snapshot is missing. A human builds it once with "
                           "`python lab/langlands/prepare_data.py` and commits lab/langlands/data/.")
    manifest = json.loads(MANIFEST.read_text(encoding="utf-8"))
    for path in (RANK_SIGNS, MURM_Q, MURM_K):
        expected = manifest.get("sha256", {}).get(path.name)
        actual = sha256_file(path)
        if actual != expected:
            raise HarnessError(f"{path.name} does not match its manifest (expected "
                               f"{str(expected)[:12]}, found {actual[:12]}). Someone changed the "
                               "data; restore it from git before continuing.")
    raw_expected = manifest.get("sources", {}).get("lmfdb_q_sqrt5", {}).get("sha256")
    if not RAW_K.exists() or sha256_file(RAW_K) != raw_expected:
        raise HarnessError(f"{RAW_K.name} is missing or does not match its manifest; restore it from git.")
    return manifest


def final_done() -> bool:
    """True once `final` has started (the test split is then spent)."""
    return FINAL_STARTED.exists() or FINAL_RESULT.exists()


# ---------------------------------------------------------------- Part B data
class RankTable:
    """The rank-0 and rank-2 classes over Q, in file order (by conductor, then class)."""

    def __init__(self) -> None:
        check_data()
        n_list, rank_list, bad_list, ap_list = [], [], [], []
        with gzip.open(RANK_SIGNS, "rt", encoding="ascii") as handle:
            header = handle.readline().rstrip("\n").split("\t")
            if header != ["N", "class", "rank", "bad", "ap25"]:
                raise HarnessError(f"unexpected columns in {RANK_SIGNS.name}: {header}")
            for line in handle:
                n, _, rank, bad, ap = line.rstrip("\n").split("\t")
                n_list.append(int(n))
                rank_list.append(int(rank))
                bad_list.append(bad)
                ap_list.append(ap)
        self.N = np.asarray(n_list, dtype=np.int64)
        self.rank = np.asarray(rank_list, dtype=np.int64)
        self.bad = bad_list
        self.ap25 = ap_list
        # Bit i set when the i-th bad prime (in increasing order) has local sign -1.
        self.mask = np.asarray([sum(1 << k for k, item in enumerate(b.split(";")) if item.endswith("-1"))
                                for b in bad_list], dtype=np.int64)
        if self.mask.max() >= 64:
            raise HarnessError("a conductor with more than six bad primes; the row key needs widening")

    def split(self, name: str) -> np.ndarray:
        """Row indices of a split, in file order."""
        bounds = {"train": (0, TRAIN_MAX_N), "val": (TRAIN_MAX_N, VAL_MAX_N),
                  "test": (VAL_MAX_N, TEST_MAX_N), "probe_fit": (0, PROBE_FIT_MAX_N),
                  "probe_check": (PROBE_FIT_MAX_N, TRAIN_MAX_N)}
        lo, hi = bounds[name]
        return np.flatnonzero((self.N >= lo) & (self.N < hi))

    def signs(self, i: int) -> list[list[int]]:
        """[[p, e, w_p], ...] for row *i*."""
        return [[int(x) for x in item.split(":")] for item in self.bad[i].split(";")]

    def records(self, idx: np.ndarray, with_rank: bool) -> list[dict]:
        """What score() receives: N and the signs, plus the rank for training rows."""
        out = []
        for i in idx:
            rec = {"N": int(self.N[i]), "bad": self.signs(int(i))}
            if with_rank:
                rec["rank"] = int(self.rank[i])
            out.append(rec)
        return out


def split_count_scores(table: RankTable, idx: np.ndarray) -> np.ndarray:
    """Frozen simple rule: how many multiplicative primes have local sign -1 (split)."""
    return np.array([sum(1 for p, e, w in table.signs(int(i)) if e == 1 and w == -1)
                     for i in idx], dtype=np.float64)


def nagao_scores(table: RankTable, idx: np.ndarray) -> np.ndarray:
    """Positive control: sum over good p < 100 of -a_p log(p) / p (uses a_p; experiments never do)."""
    weights = [math.log(p) / p for p in PRIMES_BELOW_100]
    out = np.empty(len(idx))
    for k, i in enumerate(idx):
        total = 0.0
        for wgt, a in zip(weights, table.ap25[int(i)].split(",")):
            if a:
                total -= int(a) * wgt
        out[k] = total
    return out


# ---------------------------------------------------------------- within-conductor statistics
def within_parts(scores: np.ndarray, groups: np.ndarray, positive: np.ndarray) -> dict:
    """Per-conductor pieces of the stratified Wilcoxon (Mann-Whitney) statistic.

    *groups* are conductor labels, *positive* marks rank-2 classes. Only
    conductors with both ranks contribute. Returns per-group U, pairs and
    permutation variance, and per-row midranks within each group.
    """
    scores = np.asarray(scores, dtype=np.float64)
    _, gid = np.unique(groups, return_inverse=True)
    n_groups = int(gid.max()) + 1
    n_pos = np.bincount(gid, weights=positive.astype(np.float64), minlength=n_groups)
    n_all = np.bincount(gid, minlength=n_groups).astype(np.float64)
    mixed = (n_pos > 0) & (n_pos < n_all)
    keep = mixed[gid]
    g, s, y = gid[keep], scores[keep], positive[keep]
    order = np.lexsort((s, g))
    g_sorted, s_sorted = g[order], s[order]
    m = len(g_sorted)
    first_of_group = np.r_[True, g_sorted[1:] != g_sorted[:-1]]
    group_start = np.maximum.accumulate(np.where(first_of_group, np.arange(m), 0))
    position = np.arange(m) - group_start + 1.0
    new_run = np.r_[True, (g_sorted[1:] != g_sorted[:-1]) | (s_sorted[1:] != s_sorted[:-1])]
    run_id = np.cumsum(new_run) - 1
    run_len = np.bincount(run_id).astype(np.float64)
    run_mean = np.bincount(run_id, weights=position) / run_len
    midrank_sorted = run_mean[run_id]
    midrank = np.empty(m)
    midrank[order] = midrank_sorted
    run_group = g_sorted[new_run]
    ties = np.bincount(run_group, weights=run_len ** 3 - run_len, minlength=n_groups)
    rank_sum = np.bincount(g, weights=midrank * y, minlength=n_groups)
    n2, n = n_pos, n_all
    u = rank_sum - n2 * (n2 + 1) / 2.0
    pairs = n2 * (n - n2)
    with np.errstate(divide="ignore", invalid="ignore"):
        var = np.where(mixed, pairs / 12.0 * ((n + 1) - ties / (n * (n - 1))), 0.0)
    return {"u": u[mixed], "pairs": pairs[mixed], "var": var[mixed],
            "gid": np.searchsorted(np.flatnonzero(mixed), g), "midrank": midrank, "y": y,
            "row_mask": keep}


def within_summary(parts: dict, seed: int = 0) -> dict:
    """AUC, z, one-sided p and a bootstrap interval over conductors."""
    u, pairs, var = parts["u"], parts["pairs"], parts["var"]
    total_pairs = pairs.sum()
    if total_pairs == 0:
        raise HarnessError("no conductor has both a rank-0 and a rank-2 class")
    auc = u.sum() / total_pairs
    z = (u.sum() - total_pairs / 2.0) / math.sqrt(var.sum()) if var.sum() > 0 else 0.0
    rng = np.random.default_rng(seed)
    G = len(u)
    boots = np.empty(BOOTSTRAP_DRAWS)
    for b in range(BOOTSTRAP_DRAWS):
        pick = rng.integers(0, G, G)
        boots[b] = u[pick].sum() / pairs[pick].sum()
    return {"auc_within": round(float(auc), 6), "ci95_low": round(float(np.percentile(boots, 2.5)), 6),
            "ci95_high": round(float(np.percentile(boots, 97.5)), 6), "z": round(float(z), 3),
            "p_one_sided": float(f"{0.5 * math.erfc(z / math.sqrt(2)):.3g}"),
            "pairs": int(total_pairs), "conductors": int(G)}


def paired_delta(parts_a: dict, parts_b: dict, seed: int = 0) -> dict:
    """AUC(a) - AUC(b) on the same rows, with a paired bootstrap over conductors."""
    if len(parts_a["u"]) != len(parts_b["u"]) or not np.array_equal(parts_a["pairs"], parts_b["pairs"]):
        raise HarnessError("paired comparison needs the same rows")
    du = parts_a["u"] - parts_b["u"]
    pairs = parts_a["pairs"]
    rng = np.random.default_rng(seed)
    G = len(du)
    boots = np.empty(BOOTSTRAP_DRAWS)
    for b in range(BOOTSTRAP_DRAWS):
        pick = rng.integers(0, G, G)
        boots[b] = du[pick].sum() / pairs[pick].sum()
    return {"delta_vs_best": round(float(du.sum() / pairs.sum()), 6),
            "delta_ci95_low": round(float(np.percentile(boots, 2.5)), 6),
            "delta_ci95_high": round(float(np.percentile(boots, 97.5)), 6)}


def permutation_p(parts: dict, draws: int = PERMUTATIONS, seed: int = 0) -> float:
    """Monte Carlo p-value: shuffle the rank labels within each conductor."""
    gid, midrank, y = parts["gid"], parts["midrank"], parts["y"].astype(np.float64)
    observed = float((midrank * y).sum())
    order = np.argsort(gid, kind="stable")
    g_sorted, y_sorted, m_sorted = gid[order], y[order], midrank[order]
    rng = np.random.default_rng(seed)
    hits = 0
    for _ in range(draws):
        perm = np.lexsort((rng.random(len(g_sorted)), g_sorted))
        hits += float((m_sorted[perm] * y_sorted).sum()) >= observed - 1e-9
    return round((hits + 1) / (draws + 1), 6)


# ---------------------------------------------------------------- static check
def docstring_nodes(tree: ast.AST) -> set[int]:
    """ids of the Constant nodes that are docstrings."""
    found = set()
    for node in ast.walk(tree):
        if isinstance(node, (ast.Module, ast.FunctionDef, ast.AsyncFunctionDef, ast.ClassDef)):
            body = getattr(node, "body", [])
            if (body and isinstance(body[0], ast.Expr) and isinstance(body[0].value, ast.Constant)
                    and isinstance(body[0].value.value, str)):
                found.add(id(body[0].value))
    return found


def module_allowed(name: str) -> bool:
    """True for an allowed top-level module or one of its allowlisted submodules."""
    parts = name.split(".")
    if parts[0] not in ALLOWED_IMPORTS:
        return False
    if len(parts) == 1:
        return True
    return len(parts) == 2 and parts[1] in ALLOWED_SUBMODULES.get(parts[0], frozenset())


def static_check_source(raw: bytes) -> list[str]:
    """Return the reasons an experiment's source is refused (empty if it is fine).

    An allowlist, read from the parsed code: only the listed modules and
    submodules may be imported; nothing that opens files, inspects the
    interpreter or reaches around the harness may be named, as a bare name
    or as an attribute; attribute names may not start with an underscore;
    no string may contain a double underscore; and the file may not carry
    large tables of numbers or text (which could smuggle in labels).
    """
    problems: list[str] = []
    if len(raw) > MAX_EXPERIMENT_BYTES:
        problems.append(f"file is {len(raw)} bytes (limit {MAX_EXPERIMENT_BYTES})")
    try:
        tree = ast.parse(raw.decode("utf-8"))
    except (SyntaxError, UnicodeDecodeError, ValueError) as exc:
        return problems + [f"does not parse: {exc}"]
    docs = docstring_nodes(tree)
    banned_words = BANNED_NAMES | BANNED_ATTRIBUTES
    numbers = 0
    string_chars = 0
    for node in ast.walk(tree):
        if isinstance(node, ast.Import):
            for alias in node.names:
                if not module_allowed(alias.name):
                    problems.append(f"import {alias.name}")
        elif isinstance(node, ast.ImportFrom):
            if node.level or not module_allowed(node.module or ""):
                problems.append(f"from {'.' * node.level}{node.module or ''} import")
            for alias in node.names:
                if alias.name == "*":
                    problems.append("import *")
                elif alias.name in banned_words or alias.name.startswith("_"):
                    problems.append(f"import of {alias.name}")
        elif isinstance(node, ast.Name):
            if node.id in banned_words or (node.id.startswith("__") and node.id != "__name__"):
                problems.append(f"name {node.id}")
        elif isinstance(node, ast.Attribute):
            if node.attr in BANNED_ATTRIBUTES or node.attr.startswith("_"):
                problems.append(f"attribute .{node.attr}")
        elif isinstance(node, (ast.List, ast.Tuple, ast.Set)):
            if len(node.elts) > MAX_LITERAL_ELEMENTS:
                problems.append(f"a literal with {len(node.elts)} elements (limit {MAX_LITERAL_ELEMENTS})")
        elif isinstance(node, ast.Dict):
            if len(node.keys) > MAX_LITERAL_ELEMENTS:
                problems.append(f"a dict literal with {len(node.keys)} entries (limit {MAX_LITERAL_ELEMENTS})")
        elif isinstance(node, ast.Constant):
            value = node.value
            if isinstance(value, (int, float, complex)) and not isinstance(value, bool):
                numbers += 1
                if isinstance(value, int) and abs(value) > MAX_INT_MAGNITUDE:
                    problems.append("an integer constant larger than 2**63")
            elif isinstance(value, bytes):
                problems.append("a bytes constant")
            elif isinstance(value, str) and id(node) not in docs:
                string_chars += len(value)
                if len(value) > MAX_STRING_CONSTANT:
                    problems.append(f"a string constant of {len(value)} characters (limit {MAX_STRING_CONSTANT})")
                if "__" in value:
                    problems.append("a string containing a double underscore")
    if numbers > MAX_NUMERIC_CONSTANTS:
        problems.append(f"{numbers} numeric constants (limit {MAX_NUMERIC_CONSTANTS})")
    if string_chars > MAX_STRING_CHARS:
        problems.append(f"{string_chars} characters of string constants (limit {MAX_STRING_CHARS})")
    return sorted(set(problems))


def static_check(path: Path) -> list[str]:
    """static_check_source() for a file on disk (used by humans and tests)."""
    return static_check_source(path.read_bytes())


# ---------------------------------------------------------------- running an experiment
def children_cpu() -> float:
    """CPU seconds used so far by finished child processes (0 where unmeasurable)."""
    if resource is None:
        return 0.0
    usage = resource.getrusage(resource.RUSAGE_CHILDREN)
    return usage.ru_utime + usage.ru_stime


def kill_group(proc: subprocess.Popen) -> None:
    """Kill the runner and anything it started."""
    try:
        if os.name == "posix":
            os.killpg(proc.pid, signal.SIGKILL)
        else:  # pragma: no cover - Windows
            proc.kill()
    except (ProcessLookupError, PermissionError, OSError):
        pass
    try:
        proc.wait(10)
    except subprocess.TimeoutExpired:  # pragma: no cover
        pass


def wait_for(lines: queue.Queue, kind_wanted: str, timeout: float, stderr):
    """Wait for one protocol line; explain anything else."""
    end = time.monotonic() + timeout
    while True:
        remaining = end - time.monotonic()
        if remaining <= 0:
            raise HarnessError(f"no {kind_wanted.lower()} within {timeout:.0f} s; the run was stopped.")
        try:
            stamp, kind, payload = lines.get(timeout=remaining)
        except queue.Empty:
            continue
        if kind == kind_wanted:
            return stamp, payload
        if kind == "ERROR":
            try:
                detail = json.loads(payload)
            except ValueError:
                detail = payload
            raise HarnessError(f"score() raised an error:\n{detail}")
        if kind == "EOF":
            stderr.seek(0)
            tail = stderr.read()[-1500:].decode("utf-8", "replace")
            raise HarnessError(f"the experiment process ended without an answer.\n{tail}")


def runner_env() -> dict[str, str]:
    """A minimal environment for the experiment's process (no keys or tokens)."""
    env = {"OMP_NUM_THREADS": "1", "OPENBLAS_NUM_THREADS": "1", "MKL_NUM_THREADS": "1",
           "NUMEXPR_NUM_THREADS": "1", "PYTHONHASHSEED": "0", "LOKY_MAX_CPU_COUNT": "1"}
    for name in ("PATH", "SYSTEMROOT", "WINDIR", "TEMP", "TMP", "TMPDIR", "LANG", "LC_ALL"):
        if name in os.environ:
            env[name] = os.environ[name]
    return env


def run_experiment(source: bytes, train: list[dict], rows: list[dict], seed: int) -> tuple[np.ndarray, float, float]:
    """Run score(train, rows, seed) from *source* (the exact bytes that were checked and
    hashed) in its own process; return scores, seconds and CPU seconds."""
    token = secrets.token_hex(16)
    message = json.dumps({"token": token, "seed": seed, "train": train, "rows": rows},
                         separators=(",", ":")).encode("utf-8")
    env = runner_env()
    lines: queue.Queue = queue.Queue()
    prefix = token.encode("ascii") + b" "
    with tempfile.TemporaryDirectory() as tmp:
        code_path = Path(tmp) / "experiment_under_test.py"
        code_path.write_bytes(source)
        with open(Path(tmp) / "stderr.txt", "w+b") as stderr:
            cpu_before = children_cpu()
            extra = {"start_new_session": True} if os.name == "posix" else {}
            started_at = time.monotonic()
            proc = subprocess.Popen([sys.executable, "-E", str(RUNNER), str(code_path)],
                                    stdin=subprocess.PIPE, stdout=subprocess.PIPE, stderr=stderr,
                                    cwd=tmp, env=env, **extra)

            def reader() -> None:
                assert proc.stdout is not None
                for raw in proc.stdout:
                    if raw.startswith(prefix):
                        kind, _, payload = raw[len(prefix):].decode("utf-8", "replace").partition(" ")
                        lines.put((time.monotonic(), kind.strip(), payload))
                lines.put((time.monotonic(), "EOF", ""))

            threading.Thread(target=reader, daemon=True).start()

            def writer() -> None:
                try:
                    assert proc.stdin is not None
                    proc.stdin.write(message)
                    proc.stdin.close()
                except (BrokenPipeError, OSError):
                    pass

            threading.Thread(target=writer, daemon=True).start()
            try:
                ready_at, _ = wait_for(lines, "READY", READY_TIMEOUT_S, stderr)
                done_at, payload = wait_for(lines, "RESULT", TIME_LIMIT_S, stderr)
            finally:
                kill_group(proc)
            cpu = children_cpu() - cpu_before
    wall = done_at - started_at
    if resource is not None and cpu > CPU_FACTOR * wall + CPU_GRACE_S:
        raise HarnessError(f"used {cpu:.0f} CPU seconds in {wall:.0f} s of wall time; experiments "
                           "must use one core.")
    try:
        scores = np.asarray(json.loads(payload), dtype=np.float64)
    except ValueError as exc:
        raise HarnessError(f"the answer could not be read ({exc}).") from exc
    if scores.shape != (len(rows),):
        raise HarnessError(f"score() returned {scores.size} scores for {len(rows)} rows")
    return scores, round(done_at - ready_at, 1), round(cpu, 1)


def score_split(source: bytes, table: RankTable, fit_idx: np.ndarray, eval_idx: np.ndarray,
                seed: int) -> tuple[np.ndarray, float, float]:
    """Train on *fit_idx*, score *eval_idx*; scores come back in file order.

    The data file lists classes in Cremona's class-letter order, which is
    correlated with rank, so that order must never reach an experiment. The
    training rows are handed over sorted by (N, sign pattern, rank), which is
    a function of what each row already shows. The rows to score are handed
    over once per distinct (N, sign pattern), sorted, and every class with
    that pattern receives the same score; classes with the same N and the
    same signs are indistinguishable, so a fair score could not separate
    them anyway. Everything is deterministic: the same code and seed give the
    same numbers on every run.
    """
    train_order = np.lexsort((table.rank[fit_idx], table.mask[fit_idx], table.N[fit_idx]))
    train = table.records(fit_idx[train_order], with_rank=True)
    keys = table.N[eval_idx] * 64 + table.mask[eval_idx]        # at most 6 bad primes below 500,000
    unique_keys, first, inverse = np.unique(keys, return_index=True, return_inverse=True)
    rows = table.records(eval_idx[first], with_rank=False)
    unique_scores, seconds, cpu = run_experiment(source, train, rows, seed)
    return unique_scores[inverse.ravel()], seconds, cpu


@contextlib.contextmanager
def eval_lock():
    """Run one evaluation at a time (memory and CPU); budget checks and ledger writes too."""
    RUNS_DIR.mkdir(parents=True, exist_ok=True)
    if fcntl is None:  # Windows: a local check only; the lab itself runs on Linux.
        yield
        return
    with open(LOCK, "w") as handle:
        try:
            fcntl.flock(handle, fcntl.LOCK_EX | fcntl.LOCK_NB)
        except BlockingIOError:
            print("Another evaluation is running; waiting for it to finish ...", flush=True)
            fcntl.flock(handle, fcntl.LOCK_EX)
        try:
            yield
        finally:
            fcntl.flock(handle, fcntl.LOCK_UN)


# ---------------------------------------------------------------- ledger
def git_commit() -> str:
    """Return the short git commit of the repository, or '' if unavailable."""
    try:
        out = subprocess.run(["git", "-C", str(REPO_ROOT), "rev-parse", "--short", "HEAD"],
                             capture_output=True, text=True, timeout=10)
        return out.stdout.strip()
    except (OSError, subprocess.SubprocessError):
        return ""


def read_ledger() -> list[dict[str, str]]:
    """Return the ledger rows (empty if there is no ledger yet)."""
    if not LEDGER.exists():
        return []
    with open(LEDGER, encoding="utf-8", newline="") as handle:
        return list(csv.DictReader(handle, delimiter="\t"))


def append_ledger(row: dict[str, object]) -> None:
    """Append one row to the ledger, writing the header the first time."""
    RUNS_DIR.mkdir(parents=True, exist_ok=True)
    new = not LEDGER.exists()
    with open(LEDGER, "a", encoding="utf-8", newline="") as handle:
        writer = csv.DictWriter(handle, fieldnames=LEDGER_FIELDS, delimiter="\t", extrasaction="ignore")
        if new:
            writer.writeheader()
        writer.writerow({k: str(row.get(k, "")).replace("\t", " ").replace("\n", " ")
                         for k in LEDGER_FIELDS})


def relative(path: Path) -> str:
    """Show *path* relative to the repository root when possible."""
    try:
        return str(path.resolve().relative_to(REPO_ROOT))
    except ValueError:
        return str(path)


def base_row(kind: str, split: str, label: str, sha12: str, seeds: list[int], note: str) -> dict:
    """Fields shared by every ledger row."""
    prints = fingerprint()
    return {
        "utc": datetime.now(timezone.utc).strftime("%Y-%m-%dT%H:%M:%SZ"),
        "kind": kind, "split": split, "experiment": label, "experiment_sha12": sha12,
        "git_commit": git_commit(), "seeds": ",".join(map(str, seeds)),
        "harness_sha12": prints["harness"][:12], "data_sha12": prints["data"][:12], "note": note,
    }


def save_details(row: dict, scores: np.ndarray, source: bytes | None = None) -> None:
    """Keep every class's score and the exact code that ran, so anything can be re-checked."""
    DETAILS_DIR.mkdir(parents=True, exist_ok=True)
    stem = (f"{row['utc'].replace(':', '')}_{row['kind']}_{row['split']}_{Path(str(row['experiment'])).stem}"
            f"_{row.get('experiment_sha12') or 'none'}_s{row['seeds']}_{uuid.uuid4().hex[:8]}")
    record = {"row": row, "scores_file": f"{stem}.npy"}
    if source is not None:
        (DETAILS_DIR / f"{stem}.code.txt").write_bytes(source)
        record["code_file"] = f"{stem}.code.txt"
    with open(DETAILS_DIR / f"{stem}.json", "x", encoding="utf-8") as handle:
        handle.write(json.dumps(record) + "\n")
    np.save(DETAILS_DIR / f"{stem}.npy", scores.astype(np.float64))


def saved_scores(split: str, sha12: str, seed: int) -> np.ndarray | None:
    """The most recent saved scores of an experiment file (by contents) on a split and seed."""
    if not DETAILS_DIR.exists():
        return None
    found = None
    for path in sorted(DETAILS_DIR.glob("*.json")):
        record = json.loads(path.read_text(encoding="utf-8"))
        row = record["row"]
        if (row.get("split") == split and row.get("experiment_sha12") == sha12
                and row.get("seeds") == str(seed) and row.get("status") == "ok"
                and row.get("kind") in ("experiment", "recheck")):
            found = DETAILS_DIR / record["scores_file"]
    return np.load(found) if found is not None and found.exists() else None


def started(kind: str) -> int:
    """How many val runs of *kind* this ledger has started (the budget count)."""
    return sum(1 for r in read_ledger() if r["kind"] == kind and r["split"] == "val"
               and r["status"] == "started")


def best_val_auc() -> float | None:
    """Seed-0 val AUC of the current best, lab/langlands/experiment.py (None if not yet evaluated)."""
    if not DEFAULT_EXPERIMENT.exists():
        return None
    sha = sha256_file(DEFAULT_EXPERIMENT)[:12]
    values = [float(r["auc_within"]) for r in read_ledger()
              if r["split"] == "val" and r["status"] == "ok" and r["auc_within"] and r["seeds"] == "0"
              and r["kind"] == "experiment" and r["experiment_sha12"] == sha]
    return values[-1] if values else None


def highest_val_auc() -> float | None:
    """Highest seed-0 val AUC of any trial (for information; the bar is the current best)."""
    values = [float(r["auc_within"]) for r in read_ledger()
              if r["split"] == "val" and r["status"] == "ok" and r["auc_within"]
              and r["seeds"] == "0" and r["kind"] == "experiment"]
    return max(values) if values else None


def refuse_if_bad(path: Path, kind: str, split: str, seeds: list[int], note: str) -> bytes:
    """Read the experiment once, check it, and return the exact bytes that will run."""
    if not path.exists():
        raise HarnessError(f"No experiment file at {path}")
    source = path.read_bytes()
    problems = static_check_source(source)
    if problems:
        row = base_row(kind, split, relative(path), hashlib.sha256(source).hexdigest()[:12], seeds, note)
        row.update(status="refused", note=f"{note} | refused: {'; '.join(problems)}"[:500])
        with eval_lock():
            append_ledger(row)
        raise HarnessError("The experiment is refused: " + "; ".join(problems) + ". Experiments may "
                           "import only " + ", ".join(sorted(ALLOWED_IMPORTS)) + " (no file-reading "
                           "submodules), must not open files or inspect the interpreter, and must "
                           "not carry large tables.")
    return source


def evaluate(path: Path, kind: str, split: str, fit_split: str, seed: int, note: str,
             budget: int | None = None, source: bytes | None = None) -> tuple[dict, np.ndarray, dict]:
    """Train on one split, score another, record the result in the ledger.

    *source*, when given, is the exact code to run (already read and checked
    by the caller); otherwise the file is read once here.
    """
    if source is None:
        source = refuse_if_bad(path, kind, split, [seed], note)
    table = RankTable()
    fit_idx, eval_idx = table.split(fit_split), table.split(split)
    sha12 = hashlib.sha256(source).hexdigest()[:12]
    with eval_lock():
        if budget is not None and started(kind) >= budget:
            raise HarnessError(f"The {kind} budget of {budget} is used up.")
        row = base_row(kind, split, relative(path), sha12, [seed], note)
        append_ledger({**row, "status": "started"})
        try:
            scores, seconds, cpu = score_split(source, table, fit_idx, eval_idx, seed)
        except HarnessError as exc:
            row.update(status="invalid", note=f"{note} | {exc}"[:500])
            append_ledger(row)
            raise
        parts = within_parts(scores, table.N[eval_idx], table.rank[eval_idx] == 2)
        row.update(within_summary(parts), seconds=seconds, cpu_seconds=cpu, status="ok")
        if split == "val" and DEFAULT_EXPERIMENT.exists():
            best_sha = sha256_file(DEFAULT_EXPERIMENT)[:12]
            best = saved_scores("val", best_sha, seed) if best_sha != sha12 else None
            if best is not None:
                best_parts = within_parts(best, table.N[eval_idx], table.rank[eval_idx] == 2)
                row.update(paired_delta(parts, best_parts))
        append_ledger(row)
        if split in ("val", "test"):
            save_details(row, scores, source)
    return row, scores, parts


# ---------------------------------------------------------------- Part A: murmurations
def murmuration_arrays(path: Path, key: str, lo: int, hi: int, sign_of) -> dict:
    """Per-conductor sums of sign * a / sqrt(p) and counts in each x = p/N bin.

    *sign_of(record)* returns the +1/-1 weight or None to skip the class.
    Also returns the unweighted sums split by w for the mirror-image check.
    """
    by_cond: dict[int, np.ndarray] = {}
    classes = 0
    with gzip.open(path, "rt", encoding="ascii") as handle:
        for line in handle:
            rec = json.loads(line)
            cond = rec[key]
            if not lo <= cond < hi:
                continue
            sign = sign_of(rec)
            if sign is None:
                continue
            classes += 1
            acc = by_cond.setdefault(cond, np.zeros((6, BINS)))
            plus = rec["w"] == 1
            for p, a in rec["ap"]:
                if p > cond:
                    continue
                b = min(BINS - 1, int(BINS * p / cond))
                v = a / math.sqrt(p)
                acc[0, b] += sign * v
                acc[1, b] += 1
                acc[2 if plus else 4, b] += v
                acc[3 if plus else 5, b] += 1
    if not by_cond:
        raise HarnessError(f"no classes in [{lo}, {hi}) in {path.name}")
    conds = sorted(by_cond)
    return {"stack": np.stack([by_cond[c] for c in conds]), "conductors": len(conds), "classes": classes}


def profiles(stack: np.ndarray) -> dict[str, np.ndarray]:
    """Weighted profile and the w = +1 / w = -1 profiles from per-conductor sums."""
    s = stack.sum(axis=0)
    with np.errstate(divide="ignore", invalid="ignore"):
        return {"weighted": s[0] / s[1], "plus": s[2] / s[3], "minus": s[4] / s[5]}


def corr(a: np.ndarray, b: np.ndarray) -> float:
    """Pearson correlation of two 10-bin profiles (nan if undefined)."""
    if not (np.all(np.isfinite(a)) and np.all(np.isfinite(b))) or a.std() == 0 or b.std() == 0:
        return float("nan")
    return float(np.corrcoef(a, b)[0, 1])


def interval(values: list[float], required: bool = True) -> list[float] | None:
    """95 percent percentile interval, ignoring undefined draws.

    For a primary statistic (*required*) too many undefined draws is an
    error; for a secondary one the interval is reported as undefined (None).
    """
    arr = np.asarray([v for v in values if math.isfinite(v)])
    if arr.size < 0.9 * len(values):
        if not required:
            return None
        raise HarnessError(f"only {arr.size} of {len(values)} bootstrap draws were defined; "
                           "the interval would not be meaningful")
    return [round(float(np.percentile(arr, 2.5)), 4), round(float(np.percentile(arr, 97.5)), 4)]


def strict_sign_changes(values: np.ndarray) -> int:
    """Changes between strictly positive and strictly negative bins (zeros skipped)."""
    signs = [v > 0 for v in values if v != 0]
    return sum(1 for a, b in zip(signs, signs[1:]) if a != b)


def rational_model_classes() -> set[str]:
    """Isogeny classes over Q(sqrt 5) with a curve whose LMFDB model has rational coefficients.

    Such a curve is a base change of a curve over Q. Used only for a
    sensitivity check (base changes inherit Q's a_p at split primes); the
    proxy misses base changes whose stored model is not rational.
    """
    found = set()
    with open(RAW_K, encoding="utf-8") as handle:
        for line in handle:
            if not line.startswith('"'):
                continue
            fields = line.rstrip("\n").split("\t")
            if all(c1 == 0 for _, c1 in json.loads(fields[9])):
                found.add(json.loads(fields[1]))
    return found


def murmuration_study(q_range: tuple[int, int], k_range: tuple[int, int]) -> dict:
    """C1 and C2 on the given conductor ranges (see the module docstring)."""
    check_data()
    q = murmuration_arrays(MURM_Q, "N", *q_range, sign_of=lambda r: r["w"])
    k_ss = murmuration_arrays(MURM_K, "norm", *k_range, sign_of=lambda r: r["finite_sign"])
    k_all = murmuration_arrays(MURM_K, "norm", *k_range, sign_of=lambda r: r["w"])
    rational = rational_model_classes()
    k_nobc = murmuration_arrays(MURM_K, "norm", *k_range,
                                sign_of=lambda r: None if r["class"] in rational else r["finite_sign"])
    pq, pss, pall = profiles(q["stack"]), profiles(k_ss["stack"]), profiles(k_all["stack"])
    f_nobc = profiles(k_nobc["stack"])["weighted"]
    m_q, f_ss, f_all = pq["weighted"], pss["weighted"], pall["weighted"]
    # One generator per resampled set, so adding a statistic never moves another.
    rng_q, rng_ss, rng_all, rng_nobc = (np.random.default_rng([0, k]) for k in range(4))
    boot = {"mirror": [], "rho_ss": [], "rho_all": [], "rho_nobc": [], "mq_first": [], "fss_first": []}
    for _ in range(BOOTSTRAP_DRAWS):
        bq = profiles(q["stack"][rng_q.integers(0, q["conductors"], q["conductors"])])
        bss = profiles(k_ss["stack"][rng_ss.integers(0, k_ss["conductors"], k_ss["conductors"])])
        ball = profiles(k_all["stack"][rng_all.integers(0, k_all["conductors"], k_all["conductors"])])
        bnobc = profiles(k_nobc["stack"][rng_nobc.integers(0, k_nobc["conductors"], k_nobc["conductors"])])
        boot["mirror"].append(corr(bq["plus"], bq["minus"]))
        boot["rho_ss"].append(corr(bss["weighted"], bq["weighted"]))
        boot["rho_all"].append(corr(ball["weighted"], bq["weighted"]))
        boot["rho_nobc"].append(corr(bnobc["weighted"], bq["weighted"]))
        boot["mq_first"].append(float(bq["weighted"][0]))
        boot["fss_first"].append(float(bss["weighted"][0]))
    sign_changes = strict_sign_changes(m_q)
    mirror = corr(pq["plus"], pq["minus"])
    mirror_ci = interval(boot["mirror"])
    rho_ss, rho_ss_ci = corr(f_ss, m_q), interval(boot["rho_ss"])
    rho_all, rho_all_ci = corr(f_all, m_q), interval(boot["rho_all"], required=False)
    reproduced = mirror_ci[1] < 0 and sign_changes >= 1
    if rho_ss_ci[0] > 0:
        verdict = "consistent with the predicted flip"
    elif rho_ss_ci[1] < 0:
        verdict = "contradicts the prediction"
    else:
        verdict = "inconclusive"
    edges = [f"[{b / BINS:.1f}, {(b + 1) / BINS:.1f}{']' if b == BINS - 1 else ')'}" for b in range(BINS)]
    r = lambda arr: [round(float(v), 4) for v in arr]  # noqa: E731
    return {
        "bins_x_equals_p_over_N": edges,
        "C1_Q": {"conductor_range": list(q_range), "classes": q["classes"], "conductors": q["conductors"],
                 "M_Q": r(m_q), "P_plus": r(pq["plus"]), "P_minus": r(pq["minus"]),
                 "mirror_corr_P_plus_P_minus": round(mirror, 4), "mirror_ci95": mirror_ci,
                 "M_Q_sign_changes": sign_changes, "M_Q_first_bin_ci95": interval(boot["mq_first"], required=False),
                 "reproduced": bool(reproduced)},
        "C2_Q_sqrt5": {"norm_range": list(k_range),
                       "semistable_classes": k_ss["classes"], "semistable_norms": k_ss["conductors"],
                       "all_classes": k_all["classes"], "all_norms": k_all["conductors"],
                       "F_ss": r(f_ss), "F_all": r(f_all),
                       "rho_ss": round(rho_ss, 4), "rho_ss_ci95": rho_ss_ci,
                       "rho_all": round(rho_all, 4), "rho_all_ci95": rho_all_ci,
                       "sensitivity_semistable_without_rational_models": {
                           "classes": k_nobc["classes"], "F": r(f_nobc),
                           "rho": round(corr(f_nobc, m_q), 4),
                           "rho_ci95": interval(boot["rho_nobc"], required=False)},
                       "F_ss_first_bin_ci95": interval(boot["fss_first"], required=False),
                       "verdict": verdict},
    }


# ---------------------------------------------------------------- commands
def cmd_fingerprint(_: argparse.Namespace) -> int:
    print(json.dumps(fingerprint(), indent=2))
    return 0


def cmd_describe(_: argparse.Namespace) -> int:
    manifest = check_data()
    table = RankTable()
    info = {
        "question_part_B": "Within the same conductor N, do the local root numbers (w_p) of rank-2 "
                           "classes differ from those of rank-0 classes? Metric: within-conductor AUC "
                           "on val (0.5 = no dependence), higher is better.",
        "question_part_A": "Fixed measurements C1 (murmurations over Q by root number) and C2 (the "
                           "predicted flip over Q(sqrt 5)); pilot ranges via `murmurations`, "
                           "confirmatory ranges once via `final`.",
        "splits": {"train (N < 300,000)": {"classes": int(len(table.split("train"))),
                                            "rank2": int((table.rank[table.split("train")] == 2).sum())},
                   "val (300,000 <= N < 400,000)": {"classes": int(len(table.split("val")))},
                   "test (400,000 <= N < 500,000)": {"classes": int(len(table.split("test")))}},
        "score_signature": "score(train, rows, seed) -> one float per row (higher = more likely rank 2)",
        "train_row": {"N": 11, "bad": [[11, 1, -1]], "rank": 0},
        "row": {"N": 11, "bad": [[11, 1, -1]]},
        "allowed_imports": sorted(ALLOWED_IMPORTS),
        "time_limit_seconds": TIME_LIMIT_S,
        "experiment_budget": EXPERIMENT_BUDGET, "experiments_used": started("experiment"),
        "recheck_budget": RECHECK_BUDGET, "rechecks_used": started("recheck"),
        "recheck_seeds": list(RECHECK_SEEDS),
        "current_best_val_auc_within (experiment.py)": best_val_auc(),
        "highest_val_auc_within_any_trial": highest_val_auc(),
        "keep_rule": f"val AUC at least {KEEP_MIN_GAIN} above the current best and delta_ci95_low > 0",
        "final_done": final_done(),
        "data_counts": manifest.get("counts"),
    }
    print(json.dumps(info, indent=2))
    return 0


def frozen_rule_row(name: str, split: str, scores: np.ndarray, table: RankTable, idx: np.ndarray,
                    note: str) -> tuple[dict, dict]:
    parts = within_parts(scores, table.N[idx], table.rank[idx] == 2)
    row = base_row("baseline", split, f"{name} (in harness)", "", [0], note)
    row.update(within_summary(parts), status="ok")
    return row, parts


def cmd_baselines(_: argparse.Namespace) -> int:
    """Score the frozen simple rule and the positive control on val."""
    table = RankTable()
    idx = table.split("val")
    out = {}
    for name, fn, note in (("split_count", split_count_scores, "simple rule: split multiplicative primes"),
                           ("nagao_ap25", nagao_scores, "positive control: a_p at good p < 100")):
        row, _ = frozen_rule_row(name, "val", fn(table, idx), table, idx, note)
        with eval_lock():
            append_ledger(row)
        out[name] = {k: row[k] for k in ("auc_within", "ci95_low", "ci95_high", "z", "p_one_sided",
                                         "pairs", "conductors")}
    print("BASELINES " + json.dumps(out))
    return 0


def cmd_murmurations(_: argparse.Namespace) -> int:
    """C1 and C2 on the pilot ranges (free; the confirmatory ranges are for `final`)."""
    result = murmuration_study(Q_PILOT, K_PILOT)
    print("PILOT " + json.dumps(result))
    return 0


def cmd_probe(args: argparse.Namespace) -> int:
    """Free check inside train: fit below N = 200,000, score 200,000 to 300,000."""
    row, _, _ = evaluate(Path(args.experiment).resolve(), "probe", "probe_check", "probe_fit",
                         args.seed, args.note or "")
    print("PROBE " + json.dumps(row))
    return 0


def cmd_evaluate(args: argparse.Namespace) -> int:
    best = best_val_auc()
    row, _, _ = evaluate(Path(args.experiment).resolve(), "experiment", "val", "train", SEED,
                         args.note or "", budget=EXPERIMENT_BUDGET)
    row["best_previous_auc_within"] = best
    row["experiments_used"] = started("experiment")
    print("RESULT " + json.dumps(row))
    return 0


def cmd_recheck(args: argparse.Namespace) -> int:
    """Re-run an evaluated file on val with seeds 1 and 2, for the Skeptic."""
    path = Path(args.experiment).resolve()
    source = refuse_if_bad(path, "recheck", "val", list(RECHECK_SEEDS), args.note or "")
    sha = hashlib.sha256(source).hexdigest()[:12]
    if not any(r["kind"] == "experiment" and r["split"] == "val" and r["status"] == "ok"
               and r["experiment_sha12"] == sha for r in read_ledger()):
        raise HarnessError("Recheck only a file that `evaluate` has already scored (same contents).")
    rows = []
    for seed in RECHECK_SEEDS:
        if started("recheck") >= RECHECK_BUDGET:
            raise HarnessError(f"The recheck budget of {RECHECK_BUDGET} is used up.")
        row, _, _ = evaluate(path, "recheck", "val", "train", seed, args.note or "",
                             budget=RECHECK_BUDGET, source=source)
        rows.append(row)
    summary = {"experiment": relative(path), "experiment_sha12": sha,
               "seeds": list(RECHECK_SEEDS),
               "auc_within_by_seed": [r["auc_within"] for r in rows],
               "mean_auc_within": round(float(np.mean([r["auc_within"] for r in rows])), 6),
               "delta_vs_best_by_seed": [r.get("delta_vs_best") for r in rows],
               "rechecks_used": started("recheck")}
    print("RECHECK " + json.dumps(summary))
    return 0


def cmd_final(args: argparse.Namespace) -> int:
    path = Path(args.experiment).resolve()
    if path != DEFAULT_EXPERIMENT.resolve():
        raise HarnessError("`final` scores lab/langlands/experiment.py, the promoted experiment, and nothing else.")
    source = refuse_if_bad(path, "final", "test", [SEED], args.note or "")
    check_data()
    RUNS_DIR.mkdir(parents=True, exist_ok=True)
    if final_done():
        raise HarnessError(f"The test split was already used ({relative(FINAL_STARTED)}). The final "
                           "result is reported once; it is never re-run to get a better number.")
    result: dict[str, object] = {"fingerprint": fingerprint(),
                                 "experiment_sha256": hashlib.sha256(source).hexdigest(),
                                 "definitions": {"alpha_one_sided": ALPHA, "seed": SEED,
                                                 "bootstrap_draws": BOOTSTRAP_DRAWS,
                                                 "permutations": PERMUTATIONS,
                                                 "test_conductors": [VAL_MAX_N, TEST_MAX_N]}}
    # Part A never reads the test split, so it runs before the split is marked as used.
    print("Part A: murmurations on the confirmatory ranges ...", flush=True)
    result["part_A"] = murmuration_study(Q_CONFIRM, K_CONFIRM)
    (RUNS_DIR / "final_part_A.json").write_text(json.dumps(result, indent=2) + "\n", encoding="utf-8")
    print(json.dumps(result["part_A"]), flush=True)
    try:
        # Created before Part B runs: an interrupted Part B still counts as used.
        with open(FINAL_STARTED, "x", encoding="utf-8") as handle:
            handle.write(json.dumps({"utc": datetime.now(timezone.utc).isoformat(),
                                     "experiment_sha256": hashlib.sha256(source).hexdigest()}) + "\n")
    except FileExistsError:
        raise HarnessError(f"The test split was already used ({relative(FINAL_STARTED)}).") from None
    print("Part B: training experiment.py on train + val, scoring test ...", flush=True)
    table = RankTable()
    fit_idx = np.flatnonzero(table.N < VAL_MAX_N)
    test_idx = table.split("test")
    y = table.rank[test_idx] == 2
    with eval_lock():
        row = base_row("final", "test", relative(path), hashlib.sha256(source).hexdigest()[:12], [SEED],
                       args.note or "final")
        append_ledger({**row, "status": "started"})
        try:
            scores, seconds, cpu = score_split(source, table, fit_idx, test_idx, SEED)
        except HarnessError as exc:
            row.update(status="invalid", note=f"{row['note']} | {exc}"[:500])
            append_ledger(row)
            raise
        exp_parts = within_parts(scores, table.N[test_idx], y)
        row.update(within_summary(exp_parts), seconds=seconds, cpu_seconds=cpu, status="ok")
        append_ledger(row)
        save_details(row, scores, source)
    exp = {k: row[k] for k in ("auc_within", "ci95_low", "ci95_high", "z", "p_one_sided", "pairs",
                               "conductors")}
    exp["permutation_p"] = permutation_p(exp_parts)
    rule_row, rule_parts = frozen_rule_row("split_count", "test", split_count_scores(table, test_idx),
                                           table, test_idx, "final: simple rule")
    ctrl_row, _ = frozen_rule_row("nagao_ap25", "test", nagao_scores(table, test_idx), table, test_idx,
                                  "final: positive control")
    with eval_lock():
        append_ledger(rule_row)
        append_ledger(ctrl_row)
    rule = {k: rule_row[k] for k in exp if k in rule_row}
    rule["permutation_p"] = permutation_p(rule_parts)
    control = {k: ctrl_row[k] for k in ("auc_within", "ci95_low", "ci95_high", "z", "pairs")}
    result["part_B"] = {
        "test_classes": int(len(test_idx)), "test_rank2": int(y.sum()),
        "H_B1_simple_rule": {**rule, "supported": bool(rule["p_one_sided"] < ALPHA
                                                       and rule["permutation_p"] < ALPHA)},
        "H_B2_experiment": {**exp, "supported": bool(exp["p_one_sided"] < ALPHA
                                                     and exp["permutation_p"] < ALPHA)},
        "experiment_minus_simple_rule": {k.replace("delta_vs_best", "delta").replace("delta_ci", "ci"): v
                                         for k, v in paired_delta(exp_parts, rule_parts).items()},
        "positive_control_nagao_ap25": control,
    }
    FINAL_RESULT.write_text(json.dumps(result, indent=2) + "\n", encoding="utf-8")
    print("FINAL " + json.dumps(result))
    return 0


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(description="Artemis Langlands harness (frozen).")
    sub = parser.add_subparsers(dest="command", required=True)
    sub.add_parser("fingerprint", help="SHA-256 of harness, runner and data")
    sub.add_parser("describe", help="the questions, splits and budgets")
    sub.add_parser("baselines", help="score the simple rule and the positive control on val")
    sub.add_parser("murmurations", help="C1 and C2 on the pilot ranges (free)")
    p = sub.add_parser("probe", help="free check inside train (fit N < 200,000, score 200,000-300,000)")
    p.add_argument("--experiment", default=str(DEFAULT_EXPERIMENT))
    p.add_argument("--seed", type=int, default=0)
    p.add_argument("--note", default="")
    p = sub.add_parser("evaluate", help="score one experiment on val (counts toward the budget)")
    p.add_argument("--experiment", default=str(DEFAULT_EXPERIMENT))
    p.add_argument("--note", default="")
    p = sub.add_parser("recheck", help="re-run an evaluated file on val with seeds 1 and 2 (Skeptic)")
    p.add_argument("--experiment", default=str(DEFAULT_EXPERIMENT))
    p.add_argument("--note", default="")
    p = sub.add_parser("final", help="Part A confirmatory ranges and Part B test, once")
    p.add_argument("--experiment", default=str(DEFAULT_EXPERIMENT))
    p.add_argument("--note", default="")
    args = parser.parse_args(argv)
    handlers = {"fingerprint": cmd_fingerprint, "describe": cmd_describe, "baselines": cmd_baselines,
                "murmurations": cmd_murmurations, "probe": cmd_probe, "evaluate": cmd_evaluate,
                "recheck": cmd_recheck, "final": cmd_final}
    try:
        return handlers[args.command](args)
    except HarnessError as exc:
        print(f"HARNESS: {exc}")
        return 1


if __name__ == "__main__":
    sys.exit(main())
