"""Frozen runner: executes one experiment's score() in a clean process.

DO NOT EDIT THIS FILE. It is part of the harness fingerprint.

The harness starts this script with `python -E` (PYTHON* variables ignored),
in a new process group, from an empty temporary folder, with a minimal
environment. The script removes its own folder from the import path, so an
experiment cannot import the harness. It reads one JSON message on stdin (the
training classes with their ranks, the rows to score, the seed and a one-time
token), imports the experiment from the copy the harness checked, prints
"<token> READY", calls score(train, rows, seed), and prints
"<token> RESULT <scores as JSON>". The harness, not this process, measures the
time between those two lines. The token keeps anything the experiment prints
from being mistaken for a protocol line.

Defence in depth behind the harness's static check: before the experiment is
imported, NumPy, SciPy and scikit-learn are imported and an audit hook is
installed. From then on the process may open files only for reading and only
inside the Python installation (so libraries can still load their own
modules) or the experiment's own copy; it may not start processes, open
network connections or change the hook.
"""

import importlib.util
import json
import math
import os
import random
import sys
import traceback
from pathlib import Path

import numpy as np

PREIMPORT = ("scipy", "scipy.stats", "scipy.special", "scipy.optimize", "scipy.sparse",
             "scipy.linalg", "sklearn", "sklearn.linear_model", "sklearn.ensemble",
             "sklearn.preprocessing", "sklearn.metrics", "sklearn.tree")
DENIED_EVENTS = ("subprocess.Popen", "os.system", "os.exec", "os.posix_spawn", "os.spawn",
                 "os.fork", "os.forkpty", "pty.spawn", "socket.", "urllib.", "http.",
                 "ftplib.", "smtplib.", "webbrowser.", "sys.addaudithook", "os.remove",
                 "os.unlink", "os.rename", "os.rmdir", "os.mkdir", "os.chmod", "os.putenv",
                 "os.unsetenv", "shutil.")


def install_guard(experiment_path):
    """Allow reads inside the Python installation and of the experiment; deny the rest."""
    roots = {os.path.normcase(os.path.realpath(p)) for p in
             (sys.prefix, sys.base_prefix, sys.exec_prefix, sys.base_exec_prefix,
              os.path.dirname(np.__file__), os.path.dirname(os.path.dirname(np.__file__)))}
    allowed_file = os.path.normcase(os.path.realpath(experiment_path))

    def inside(path):
        real = os.path.normcase(os.path.realpath(path))
        if real == allowed_file:
            return True
        for root in roots:
            try:
                if os.path.commonpath([real, root]) == root:
                    return True
            except ValueError:  # different drives on Windows
                continue
        return False

    def hook(event, args):
        if event == "open":
            path, mode, flags = (list(args) + [None, None, None])[:3]
            if isinstance(path, int):
                return                          # an already-open descriptor
            if isinstance(path, bytes):
                path = os.fsdecode(path)
            writing = (isinstance(mode, str) and any(c in mode for c in "wax+")) or (
                isinstance(flags, int) and flags & (os.O_WRONLY | os.O_RDWR | os.O_CREAT))
            if writing or not inside(str(path)):
                raise PermissionError(f"the experiment may not open {path!r}")
        elif event.startswith(DENIED_EVENTS):
            raise PermissionError(f"the experiment may not use {event}")

    sys.addaudithook(hook)


def main():
    here = str(Path(__file__).resolve().parent)
    sys.path[:] = [p for p in sys.path if p not in ("", ".", here)]
    sys.dont_write_bytecode = True
    message = json.loads(sys.stdin.read())
    token = message["token"]
    out = sys.stdout

    def emit(kind, payload=""):
        out.write(f"{token} {kind} {payload}\n")
        out.flush()

    try:
        train = message["train"]
        rows = message["rows"]
        seed = int(message["seed"])
        del message
        for name in PREIMPORT:
            importlib.import_module(name)
        random.seed(seed)
        np.random.seed(seed)
        spec = importlib.util.spec_from_file_location("artemis_experiment", sys.argv[1])
        module = importlib.util.module_from_spec(spec)
        install_guard(sys.argv[1])
        spec.loader.exec_module(module)
        if not hasattr(module, "score"):
            raise RuntimeError("the experiment must define score(train, rows, seed)")
        emit("READY")
        scores = module.score(train, rows, seed)
        clean = []
        for value in scores:
            number = float(value)
            if not math.isfinite(number):
                raise ValueError(f"score() returned a non-finite value: {value!r}")
            clean.append(number)
        emit("RESULT", json.dumps(clean))
    except BaseException:  # noqa: BLE001 - report every failure to the harness
        emit("ERROR", json.dumps(traceback.format_exc(limit=6)))


if __name__ == "__main__":
    main()
